#!/usr/bin/env python3
"""Generates 125 Observation missions across Levels 1 to 5 for missions.json."""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, "Reboot", "Content")
os.makedirs(CONTENT, exist_ok=True)

categories = [
    (1, "CONCRETE_DETAILS", "Détails concrets et signaux visuels immédiats"),
    (2, "PATTERNS", "Répétitions, flux et schémas récurrents"),
    (3, "BEHAVIOR", "Comportements humains et micro-interactions"),
    (4, "SYSTEMS", "Architectures d'incitation et logiques d'organisation"),
    (5, "HYPOTHESES", "Modélisation causale et déduction d'intentions")
]

missions = []
m_id = 1

templates = [
    # LEVEL 1 — CONCRETE DETAILS (1..25)
    ("Les trois objets immobiles", "Repère trois objets dans ton champ de vision qui n'ont pas bougé depuis au moins un an.", ["Matériau", "Usure", "Poussière"], "Pourquoi cet objet est-il resté là ?", "Intérieur / Bureau"),
    ("Les ombres portées", "Observe la direction exacte et la netteté des ombres dans la pièce.", ["Source de lumière", "Bord franc ou flou", "Contraste"], "Comment la lumière change-t-elle l'ambiance de travail ?", "Bureau / Pièce"),
    ("Les textures de surface", "Identifie cinq textures différentes au toucher sans regarder d'écran.", ["Bois", "Métal", "Tissu"], "Quel matériau favorise le plus ton calme tactile ?", "Intérieur"),
    ("Les signaux de direction", "Compte combien de flèches ou d'indications visuelles sont présentes autour de toi.", ["Flèches", "Panneaux", "Marquages"], "L'environnement te dicte-t-il ton trajet ?", "Rue / Transport"),
    ("Les reflets dans les vitres", "Regarde à travers une vitre et focalise alternativement sur le reflet et sur l'extérieur.", ["Plan focal 1", "Plan focal 2", "Superposition"], "Ton attention visuelle bascule-t-elle facilement ?", "Extérieur / Café"),
    ("La palette chromatique", "Isole les trois couleurs dominantes de l'espace où tu te trouves.", ["Teinte principale", "Accents", "Surfaces neutres"], "L'espace est-il visuellement agressif ou apaisant ?", "Espace public"),
    ("Les micro-mouvements de l'air", "Observe ce qui bouge imperceptiblement autour de toi : feuilles, rideaux, poussières.", ["Fréquence", "Amplitude", "Cause du courant"], "Le silence physique t'aide-t-il à décanter ?", "Intérieur"),
    ("Les points de contact physiques", "Prends conscience des zones de contact exactes entre ton corps et ton siège ou le sol.", ["Pression des pieds", "Appui lombaire", "Poids des bras"], "Comment ta posture influence-t-elle ta vigilance ?", "Bureau / Assise"),
    ("Les bruits de fond mécaniques", "Isole trois sons mécaniques constants que ton cerveau avait filtrés.", ["Ventilation", "Moteur lointain", "Transfo électrique"], "Quelle énergie ton cerveau dépense-t-il à filtrer ce bruit ?", "Bureau / Ville"),
    ("L'état des sols", "Observe l'usure, les traces de pas et les matériaux du sol sous tes pieds.", ["Lignes de passage", "Fissures", "Changements de revêtement"], "Où les gens marchent-ils le plus souvent ?", "Hall / Gare"),
    ("Les fenêtres et ouvertures", "Compte combien d'ouvertures vers l'extérieur sont visibles depuis ton poste.", ["Hauteur", "Lumière incidente", "Vue dégagée"], "Ton regard peut-il s'échapper à plus de 20 mètres ?", "Poste de travail"),
    ("Les objets abandonnés", "Cherche un objet manifestement oublié ou laissé de côté dans l'espace public.", ["Nature de l'objet", "Emplacement", "Temps probable"], "Qu'est-ce qui rend un objet invisible ?", "Rue / Parc"),
    ("Les étiquettes et typographies", "Examine la police de caractères utilisée sur trois emballages ou panneaux proches.", ["Sérif ou sans-sérif", "Graisse", "Lisibilité à distance"], "Quelle intention commerciale ou pratique transparaît ?", "Magasin / Bureau"),
    ("Les câbles et connexions", "Remarque le réseau de fils et de branchements sous ou derrière les tables.", ["Organisation", "Visibilité", "Sécurité"], "Le désordre technique reflète-t-il une charge mentale ?", "Espace de travail"),
    ("Les reflets d'eau ou de pluie", "Observe comment une flaque ou une surface humide déforme la lumière urbaine.", ["Ondulations", "Symétrie déformée", "Couleurs réfléchies"], "La beauté du réel dépasse-t-elle les simulations ?", "Extérieur"),
    ("Les matériaux de construction", "Distingue la pierre, le béton, le plâtre et le bois dans la structure d'un bâtiment.", ["Jointures", "Âge des matériaux", "Qualité de finition"], "Ce lieu a-t-il été construit pour durer ou pour aller vite ?", "Rue / Bâtiment"),
    ("Les sources de chaleur", "Identifie d'où provient la chaleur ou la fraîcheur dans l'espace.", ["Radiateur", "Soleil direct", "Courant d'air"], "La température de ton espace favorise-t-elle l'endormissement ?", "Intérieur"),
    ("Les seuils et portes", "Observe la manière dont les portes sont conçues : poignées, battants, vitrages.", ["Ergonomie d'ouverture", "Isolation phonique", "Hauteur de passage"], "Le seuil marque-t-il une transition mentale ?", "Entrée de lieu"),
    ("Les reflets sur les écrans éteints", "Regarde un écran noir et observe ce qu'il reflète dans la pièce.", ["Lumière d'arrière-plan", "Traces de doigts", "Positionnement"], "L'écran vide est-il un miroir de ton espace ?", "Bureau"),
    ("Les livres et tranches", "Observe l'alignement, l'épaisseur et la couleur des tranches sur une étagère.", ["Ordre de rangement", "Usure des dos", "Hauteur des volumes"], "Quelle impression de densité émane d'une bibliothèque ?", "Bibliothèque / Salon"),
    ("Les plantes et feuilles", "Examine la géométrie précise des nervures d'une plante d'intérieur.", ["Symétrie", "Épaisseur", "Orientation vers la lumière"], "La nature suit-elle des règles mathématiques strictes ?", "Intérieur / Jardin"),
    ("Les fixations murales", "Regarde comment les tableaux, étagères ou panneaux sont accrochés au mur.", ["Vis", "Chevilles", "Clous visibles"], "Ce qui tient l'espace est-il discret ou grossier ?", "Pièce à vivre"),
    ("Les variations de gris", "Compte combien de nuances de gris ou de blanc se côtoient sur un même mur.", ["Ombres douces", "Reflets de lumière", "Textures de peinture"], "Ton regard peut-il se poser sans s'agiter ?", "Espace épuré"),
    ("Les objets doubles", "Trouve deux objets identiques dans la pièce et compare leur usure respective.", ["Objet utilisé", "Objet de réserve", "Différences microscopiques"], "L'usage marque-t-il la matière ?", "Cuisine / Atelier"),
    ("La distance au premier obstacle", "Estime la distance exacte entre tes yeux et le premier obstacle visuel direct.", ["Champ proche", "Champ moyen", "Horizon"], "Tes yeux sont-ils enfermés dans un rayon de 2 mètres ?", "Bureau"),

    # LEVEL 2 — PATTERNS (26..50)
    ("Le rythme des feux de signalisation", "Chronomètre mentalement le cycle complet d'un feu tricolore.", ["Durée du rouge", "Durée du vert", "Temps de réaction des piétons"], "Comment la synchronisation urbaine régule-t-elle les foules ?", "Carrefour urbain"),
    ("La file d'attente naturelle", "Observe comment les gens se positionnent spontanément dans une queue.", ["Distance interindividuelle", "Orientation des épaules", "Consultation du téléphone"], "Quelle règle implicite gouverne l'espace personnel ?", "Gare / Boulangerie"),
    ("Les chemins de désir", "Repère une trace d'herbe piétinée coupant un chemin goudronné officiel.", ["Angle de raccourci", "Fréquentation visible", "Largeur de la trace"], "L'humain choisit-il toujours la moindre résistance ?", "Parc / Campus"),
    ("La distribution des places assises", "Observe quelles chaises ou banquettes sont occupées en premier dans un café.", ["Places adossées au mur", "Places près des fenêtres", "Places centrales"], "La recherche de sécurité guide-t-elle notre confort ?", "Café / Restaurant"),
    ("La vitesse de marche des passants", "Distingue les piétons qui ont un objectif net de ceux qui flânent.", ["Longueur de foulée", "Regard porté au loin", "Rythme de balancement des bras"], "La précipitation modifie-t-elle la perception du paysage ?", "Rue piétonne"),
    ("Les cycles de respiration collective", "Dans un espace silencieux, écoute le rythme des respirations ou des mouvements.", ["Synchronisation", "Bruits de papier", "Toux d'ajustement"], "Un groupe silencieux adopte-t-il un tempo commun ?", "Salle d'étude"),
    ("L'orientation des regards dans les transports", "Observe vers où se dirigent les yeux des passagers dans une rame.", ["Écrans individuels", "Publicités au plafond", "Regard dans le vide"], "Quel pourcentage de personnes évite tout contact visuel ?", "Métro / Train"),
    ("Le schéma de consultation des menus", "Regarde comment les clients parcourent la carte d'un restaurant.", ["Haut à droite d'abord", "Lecture diagonale", "Temps d'hésitation"], "L'architecture du menu influence-t-elle le choix ?", "Restaurant"),
    ("Les grappes de conversation", "Observe la taille des sous-groupes qui se forment spontanément dans une réunion.", ["Duos", "Trios", "Petits cercles de 4"], "Au-delà de combien de personnes le groupe se scinde-t-il ?", "Événement / Pause café"),
    ("L'alternance parole / silence", "Chronomètre la durée moyenne d'une prise de parole dans une discussion proche.", ["Monologue dominant", "Échange rapide", "Micro-pauses de réflexion"], "Qui occupe l'espace sonore et qui écoute ?", "Lieu partagé"),
    ("Les micro-ajustements de posture", "Compte combien de fois une personne assise réajuste sa position en 5 minutes.", ["Croisement de jambes", "Appui du menton", "Redressement du dos"], "L'agitation corporelle trahit-elle une fatigue mentale ?", "Bureau / Salle de cours"),
    ("L'effet d'entraînement des gestes", "Observe si le geste d'une personne (boire, sortir son téléphone) en déclenche un autre.", ["Bâillement", "Consultation d'écran", "Regard vers la porte"], "Sommes-nous des imitateurs automatiques ?", "Terrasse / Salle d'attente"),
    ("Les vagues d'arrivée et de départ", "Repère la périodicité avec laquelle un groupe entre ou quitte un lieu public.", ["Pulsations liées aux feux", "Horaires de train", "Moments de flottement"], "Comment le temps institutionnel sculpte les flux ?", "Hall de gare"),
    ("La typologie des sacs et bagages", "Catégorise les sacs portés par les passants : sac à dos, valise, sac à main, rien.", ["Volume transporté", "Matériau", "Degré d'encombrement"], "Ce que l'on transporte reflète-t-il notre rayon d'action ?", "Quartier d'affaires"),
    ("La disposition des couverts et verres", "Remarque comment les tables sont dressées avant et après le repas.", ["Symétrie initiale", "Désordre fonctionnel", "Position des serviettes"], "Le désordre suit-il une logique d'utilisation ?", "Cafétéria"),
    ("Le rythme de frappe au clavier", "Écoute la musique du tapotement de touches autour de toi.", ["Rafales rapides", "Pauses d'hésitation", "Frappe lente et lourde"], "Le tempo de frappe reflète-t-il la clarté de la pensée ?", "Open space / Bibliothèque"),
    ("Les motifs architecturaux répétés", "Trouve une série de 10 éléments architecturaux strictement identiques.", ["Barreaux", "Fenêtres", "Piliers", "Dalles"], "La répétition géométrique apaise-t-elle le regard ?", "Façade d'immeuble"),
    ("L'alternance ombre / lumière dans une allée", "Marche sous des arbres et observe le damier lumineux au sol.", ["Taches solaires", "Vent dans les branches", "Changement de contraste"], "La lumière naturelle dynamique stimule-t-elle l'éveil ?", "Parc / Allée"),
    ("Les horaires d'affluence des magasins", "Observe la densité de clients à 10 minutes d'intervalle.", ["Entrées par minute", "Files en caisse", "Taux de remplissage"], "Quelle est la fenêtre la plus calme pour faire une course ?", "Supermarché"),
    ("La distribution des âges dans un quartier", "Estime la tranche d'âge des 20 premiers passants croisés.", ["Enfants", "Étudiants", "Actifs", "Seniors"], "L'espace urbain ségrègue-t-il les générations ?", "Place publique"),
    ("Les rituels d'installation au travail", "Observe la séquence exacte de gestes d'un collègue arrivant à son bureau.", ["Pose du sac", "Allumage écran", "Remplissage gourde"], "Le rituel sert-il d'amorçage à la concentration ?", "Bureau"),
    ("Les bruits de pas selon la chaussure", "Distingue à l'oreille le son des talons, des baskets et des chaussures de cuir.", ["Impact sec", "Frottement étouffé", "Cadence"], "Peut-on identifier l'intention d'un passant sans le voir ?", "Couloir / Rue"),
    ("Les transitions feu vert / démarrage", "Mesure le temps de latence entre le passage au vert et le premier démarrage de voiture.", ["Attention du premier conducteur", "Klaxon de rappel", "Temps de réaction moyen"], "Quelle part de conducteurs consulte son téléphone au feu ?", "Carrefour"),
    ("L'organisation des rayons de librairie", "Regarde comment les couvertures sont présentées : de face ou de tranche.", ["Mise en avant visuelle", "Densité de rangement", "Hauteur des yeux"], "Ce qui est au niveau du regard se vend-il mieux ?", "Librairie"),
    ("La géométrie des ombres portées du soir", "Observe comment les ombres s'allongent dramatiquement avant le coucher du soleil.", ["Angles rasants", "Distorsion des silhouettes", "Teinte dorée"], "Le changement de spectre lumineux invite-t-il au calme ?", "Fin d'après-midi"),

    # LEVEL 3 — BEHAVIOR (51..75)
    ("Le réflexe du feu rouge piéton", "Observe combien de piétons attendent sagement et combien traversent au rouge.", ["Présence de voitures", "Effet de foule", "Consultation de téléphone en marchant"], "Quand une personne traverse, les autres la suivent-elles ?", "Passage piéton"),
    ("La posture d'évitement social", "Repère les signaux corporels indiquant qu'une personne ne veut pas être abordée.", ["Écouteurs visibles", "Regard baissé", "Bras croisés"], "Le téléphone sert-il de bouclier social protecteur ?", "Transport / Espace public"),
    ("Le geste de vérification fantôme", "Observe quelqu'un qui tapote sa poche pour vérifier la présence de son appareil.", ["Fréquence du geste", "Instant déclencheur", "Soulagement visible"], "L'angoisse de la perte est-elle devenue un tic moteur ?", "Rue / Quai"),
    ("La négociation d'espace dans une porte", "Regarde la danse silencieuse de deux personnes arrivant ensemble devant un passage étroit.", ["Ralentissement", "Contact visuel", "Geste de la main 'après vous'"], "Comment la politesse régule-t-elle les micro-conflits d'espace ?", "Entrée de magasin"),
    ("L'attention partagée parent-enfant", "Observe un échange entre un adulte et un enfant dans un parc.", ["Regard direct", "Interruption par écran", "Niveau d'écoute réel"], "La présence physique suffit-elle sans présence attentionnelle ?", "Parc / Aire de jeux"),
    ("La réaction à une notification sonore", "Dans un silence, écoute une sonnerie et observe les têtes qui se lèvent simultanément.", ["Tressaillement involontaire", "Vérification réflexe", "Perte de fil"], "Combien de personnes ont vérifié leur propre téléphone par erreur ?", "Salle d'attente / Bureau"),
    ("Le rituel de paiement en caisse", "Observe la fluidité de préparation du moyen de paiement.", ["Téléphone prêt", "Carte sortie à l'avance", "Recherche paniquée dans le sac"], "L'anticipation mentale varie-t-elle selon le niveau de stress ?", "Caisse"),
    ("Le regard des gens qui attendent seuls", "Regarde où se posent les yeux des personnes sans écran pendant 2 minutes.", ["Sol", "Passants", "Mains", "Plafond"], "L'absence d'écran crée-t-elle un inconfort visible ?", "Quai de gare"),
    ("L'écoute dans une conversation téléphonique", "Observe une personne qui parle au téléphone en marchant : ses gestes, son regard.", ["Regard vide dans le lointain", "Gesticulation inutile", "Baisse de vitesse"], "Le cerveau est-il téléporté dans l'espace de l'interlocuteur ?", "Rue"),
    ("La dynamique d'approbation dans un groupe", "Dans une réunion, observe qui hoche la tête quand le leader parle.", ["Sourires d'acquiescement", "Prise de notes mimétique", "Regard vers les autres"], "L'accord est-il sincère ou conformiste ?", "Réunion / Conférence"),
    ("Le choix de la table isolée", "Observe quelqu'un qui entre seul dans un café et choisit sa place.", ["Tour d'horizon visuel", "Recherche de prise électrique", "Orientation dos aux gens"], "Quelles sont les priorités d'un travailleur nomade ?", "Café"),
    ("La gestion d'un micro-échec en public", "Regarde comment réagit une personne qui trébuche ou fait tomber un objet.", ["Regard rapide autour", "Rire de façade", "Précipitation à ramasser"], "La peur du jugement guide-t-elle la récupération ?", "Espace public"),
    ("La manière de tenir une tasse chaude", "Observe les deux mains qui entourent une boisson chaude.", ["Recherche de réconfort tactile", "Pauses lentes", "Ralentissement global"], "Le geste physique peut-il induire un état de calme ?", "Café / Domicile"),
    ("L'entrée dans un ascenseur plein", "Regarde la redistribution spatiale instantanée de 4 personnes qui entrent.", ["Face à la porte obligatoire", "Regard fixé sur l'indicateur d'étage", "Silence strict"], "Pourquoi l'ascenseur suspend-il toute sociabilité ?", "Immeuble de bureaux"),
    ("Le feuilletage d'un magazine en salle d'attente", "Observe la vitesse à laquelle les pages sont tournées.", ["Survol distrait", "Arrêt sur une image forte", "Temps de lecture réel"], "Consomme-t-on le papier comme un flux numérique ?", "Cabinet médical"),
    ("La consultation d'horaires sur panneau", "Regarde l'expression faciale des passagers devant le grand panneau d'affichage.", ["Tension du sourcil", "Soulagement à la vue du quai", "Reprise de marche"], "L'information réduit-elle l'anxiété motrice ?", "Hall de gare"),
    ("La dégustation de la première gorgée", "Observe le visage de quelqu'un qui boit sa première gorgée de café du matin.", ["Fermeture des yeux", "Expiration de détente", "Pause avant le premier mot"], "Le rituel gustatif sert-il d'ancrage de transition ?", "Comptoir"),
    ("La marche synchronisée d'un couple", "Regarde le pas de deux personnes marchant côte à côte.", ["Pied gauche / pied droit synchrone", "Ajustement automatique du rythme", "Distance d'épaule"], "La complicité se traduit-elle par un mimétisme moteur ?", "Rue"),
    ("L'interruption par un appel urgent", "Observe la rupture d'attitude d'une personne dont le téléphone sonne.", ["Arrêt net de la marche", "Isolement physique contre un mur", "Changement de ton"], "L'appel extérieur déchire-t-il la bulle locale ?", "Trottoir"),
    ("Le regard vers sa montre", "Regarde quelqu'un consulter l'heure et demande-toi s'il sait vraiment l'heure 5 secondes après.", ["Regard fugace", "Absence d'encodage", "Geste machinal"], "Combien de gestes faisons-nous sans en retenir l'information ?", "Espace public"),
    ("La recherche de clés dans un sac", "Observe la patience ou la panique de quelqu'un devant sa porte fermée.", ["Fouille méthodique", "Secouement du sac", "Frustration croissante"], "La friction matérielle teste-t-elle le calme émotionnel ?", "Palier"),
    ("L'effacement d'un tableau blanc", "Regarde le geste régulier d'effacement de haut en bas.", ["Disparition des traces", "Blanc retrouvé", "Prêt pour la suite"], "La clôture visuelle apaise-t-elle l'esprit ?", "Salle de travail"),
    ("La réaction à un rire spontané", "Dans un lieu public, écoute un éclat de rire et observe l'effet sur les voisins.", ["Sourires contagieux", "Regard agacé", "Indifférence"], "L'émotion positive se propage-t-elle plus vite que le bruit ?", "Terrasse"),
    ("La vérification de son reflet dans une vitrine", "Observe le coup d'œil discret mais systématique des passants.", ["Ajustement de veste", "Regard furtif", "Vérification d'allure"], "L'image de soi est-elle une vigilance constante ?", "Rue commerçante"),
    ("La concentration d'un artisan ou cuisinier", "Observe les mains expertes qui découpent ou assemblent sans hésiter.", ["Économie de geste", "Regard posé 2 secondes en avance", "Fluidité continue"], "L'expertise se reconnaît-elle à l'absence de mouvements parasites ?", "Marché / Atelier"),

    # LEVEL 4 — SYSTEMS (76..100)
    ("L'architecture d'un supermarché", "Repère comment l'entrée t'oblige à parcourir les rayons frais avant les produits de base.", ["Produits d'appel au fond", "Têtes de gondole promotionnelles", "Bons plans au niveau des yeux"], "Comment l'espace physique maximise-t-il la dépense ?", "Supermarché"),
    ("Les pièges de friction des aéroports", "Observe le circuit sinueux imposé à travers la boutique duty-free avant d'atteindre les portes.", ["Passage obligé", "Lumière valorisante", "Ralentissement forcé du pas"], "Le design aéroportuaire transforme-t-il le voyageur en consommateur captif ?", "Terminal d'aéroport"),
    ("La hiérarchie des sièges dans un train", "Compare l'espace, les prises, l'orientation et la lumière entre première et seconde classe.", ["Largeur d'assise", "Isolement visuel", "Accès au silence"], "Le confort attentionnel est-il devenu un produit tarifé ?", "Gare / Train"),
    ("Le système de tri des déchets urbains", "Observe la forme des ouvertures des poubelles de tri (fente pour papier, trou pour verre).", ["Ergonomie contraignante", "Couleur normalisée", "Taux d'erreur visible"], "Le design physique peut-il forcer le bon geste sans police ?", "Espace urbain"),
    ("L'aménagement d'une bibliothèque universitaire", "Analyse la séparation entre zones silencieuses, travail en groupe et détente.", ["Règles affichées", "Matériaux insonorisants", "Disposition des tables"], "Comment l'institution protège-t-elle la ressource attentionnelle ?", "Bibliothèque"),
    ("Les boucles de circulation dans un musée", "Observe si les visiteurs suivent le sens officiel ou créent leur propre parcours.", ["Fléchage au sol", "Attraction des œuvres majeures", "Saturation des petites salles"], "La muséographie guide-t-elle la durée d'attention portée à chaque tableau ?", "Musée"),
    ("La signalétique des urgences médicales", "Regarde comment les couleurs guident les patients selon la gravité.", ["Rouge / Orange / Vert", "Lignes tracées au sol", "Lisibilité en état de panique"], "L'urgence exige-t-elle une clarté cognitive absolue ?", "Hôpital"),
    ("L'organisation d'un open space d'entreprise", "Observe la disposition des bureaux par rapport aux couloirs de passage et à la lumière.", ["Dos au couloir", "Face aux fenêtres", "Bureaux partagés sans barrière"], "L'open space favorise-t-il la communication ou la surveillance mutuelle ?", "Entreprise"),
    ("Le design des distributeurs automatiques", "Regarde la hauteur des boutons, la vitre éclairée et le bruit de chute du produit.", ["Visibilité des confiseries", "Facilité du paiement sans contact", "Récompense mécanique immédiate"], "La machine est-elle conçue pour exploiter une pulsion instantanée ?", "Station de métro"),
    ("La disposition des guichets de banque", "Observe comment la confidentialité est matérialisée dans l'espace.", ["Ligne de courtoisie au sol", "Verre dépoli", "Distance d'écoute"], "L'intimité financière exige-t-elle des barrières physiques strictes ?", "Banque / Poste"),
    ("L'architecture d'un parc public", "Analyse les transitions entre les allées larges, les pelouses ouvertes et les recoins boisés.", ["Visibilité générale", "Bancs isolés", "Points d'eau comme attracteurs"], "Le parc offre-t-il un gradient de stimulation sensorielle ?", "Parc"),
    ("La circulation dans une gare centrale", "Observe le croisement entre les flux pressés des banlieusards et les flux lents des voyageurs longue distance.", ["Vitesse différentielle", "Obstacles au milieu du hall", "Panneaux visibles de partout"], "Comment un même espace gère-t-il deux rapports au temps opposés ?", "Gare"),
    ("La signalisation des sorties de secours", "Repère les blocs lumineux verts de secours depuis n'importe quel point de la pièce.", ["Alimentation autonome", "Symbole universel du bonhomme qui court", "Visibilité dans l'obscurité"], "Le système de sécurité est-il gravé dans la mémoire spatiale du bâtiment ?", "Bâtiment public"),
    ("L'organisation d'un atelier de mécanique ou de menuiserie", "Observe le tableau d'outils avec les silhouettes dessinées à l'emplacement de chaque clé.", ["Place unique pour chaque outil", "Visibilité immédiate du manque", "Zéro temps de recherche"], "L'ordre spatial élimine-t-il la fatigue de décision ?", "Atelier"),
    ("Le système de réservation de vélos en libre-service", "Regarde la borne, le cadenas électronique et l'application mobile.", ["Friction de déverrouillage", "Disponibilité affichée", "Feedback sonore à l'accrochage"], "La simplicité du système encourage-t-elle le report modal ?", "Station de vélos"),
    ("La disposition des tables dans une terrasse de café", "Observe comment le gérant optimise le nombre de chaises tout en préservant le passage des serveurs.", ["Alignement serré", "Allée centrale dégagée", "Orientation vers le soleil"], "Le compromis économique contraint-il l'intimité des conversations ?", "Terrasse"),
    ("L'aménagement d'une pharmacie", "Distingue la zone en libre-service (parapharmacie) du comptoir sur ordonnance.", ["Éclairage clinique blanc", "Produits de confort à portée de main", "Médicaments derrière le comptoir"], "La confiance médicale se construit-elle par la séparation spatiale ?", "Pharmacie"),
    ("La régulation d'un rond-point routier", "Observe comment la priorité à gauche et la trajectoire circulaire éliminent le besoin de feux.", ["Auto-régulation par le flux", "Ralentissement géométrique forcé", "Fluidité continue"], "La contrainte de forme est-elle plus efficace que l'interdiction par signal ?", "Carrefour giratoire"),
    ("L'architecture d'une cour d'école", "Observe comment l'espace est partagé entre terrain de foot central et zones calmes périphériques.", ["Monopolisation par les jeux de ballon", "Bancs en retrait", "Surveillance visuelle globale"], "La géométrie de la cour prédétermine-t-elle les dynamiques de groupe ?", "École"),
    ("La distribution des prises électriques dans un espace de coworking", "Compte le nombre de prises disponibles par rapport au nombre de sièges.", ["Prises au sol", "Multiprises intégrées aux tables", "Guerre silencieuse pour le branchement"], "L'énergie est-elle devenue la ressource vitale qui dicte l'installation ?", "Coworking"),
    ("Le système d'affichage dynamique des abribus", "Regarde comment le temps d'attente est projeté en direct (minutes restantes).", ["Réduction de l'incertitude", "Mise à jour en temps réel", "Écran rétro-éclairé"], "Savoir exactement combien de temps on attend rend-il l'attente plus tolérable ?", "Arrêt de bus"),
    ("La disposition des produits dans une boulangerie", "Observe l'ordre d'apparition : pains de base, viennoiseries dorées, pâtisseries éclairées.", ["Attrait visuel des gâteaux", "Odeur de cuisson canalisée", "Rapidité du service baguette"], "Le parcours client est-il une progression du besoin vers la tentation ?", "Boulangerie"),
    ("La gestion des files uniques en caisse", "Compare la file unique avec appel automatique à la caisse libre aux files multiples.", ["Sentiment de justice temporelle", "Baisse de l'anxiété de choisir la mauvaise file", "Fluidité globale"], "Le design du temps d'attente modifie-t-il la perception de justice ?", "Grand magasin"),
    ("L'organisation d'un laboratoire de recherche", "Observe la stricte séparation entre paillasses humides, microscopes et bureaux informatiques.", ["Protocoles de propreté", "Zonage des risques", "Cheminements courts"], "La rigueur scientifique commence-t-elle par le cloisonnement spatial ?", "Laboratoire"),
    ("La structure d'un tribunal ou d'une salle d'audience", "Analyse la surélévation des magistrats, la position du prévenu et l'espace du public.", ["Mise en scène de l'autorité", "Acoustique imposante", "Séparation physique stricte"], "L'architecture juridique sert-elle à matérialiser la solennité de la loi ?", "Palais de justice"),

    # LEVEL 5 — HYPOTHESES & INTENTIONS (101..125)
    ("L'intention derrière l'éclairage tamisé d'un restaurant", "Formule une hypothèse sur pourquoi les tables sont éclairées par une seule bougie ou lampe basse.", ["Intimité visuelle", "Ralentissement de la consommation", "Masquage des détails de salle"], "La pénombre invite-t-elle à prolonger le séjour et augmenter l'addition ?", "Restaurant gastronomique"),
    ("La raison de l'absence d'horloges dans les casinos et centres commerciaux", "Déduis pourquoi aucune heure n'est affichée sur les murs de ces espaces.", ["Perte de repère temporel", "Immersion continue", "Suppression de la culpabilité"], "L'abolition du temps est-elle le premier outil de captation attentionnelle ?", "Centre commercial / Casino"),
    ("L'intention de l'interface d'un distributeur de billets", "Analyse pourquoi la machine te rend ta carte bancaire AVANT de distribuer les billets.", ["Élimination de l'oubli de carte", "Priorité de sécurité", "Séquençage ergonomique"], "Comment l'ingénieur protège-t-il l'utilisateur distrait contre lui-même ?", "Distributeur bancaire"),
    ("L'hypothèse des bancs publics anti-SDF", "Observe la présence d'accoudoirs intermédiaires ou d'inclinaisons sur les bancs urbains.", ["Empêcher la position allongée", "Contrôle social invisible", "Design hostile"], "L'aménagement urbain peut-il exclure certaines populations sans texte de loi ?", "Rue / Square"),
    ("La logique des prix en 0,99 €", "Pourquoi un prix se termine-t-il par 99 centimes plutôt qu'un chiffre rond ?", ["Biais du chiffre de gauche", "Impression de précision comptable", "Contrainte de rendre la monnaie"], "Notre cerveau traite-t-il les nombres de manière asymétrique ?", "Commerce"),
    ("L'intention du silence dans les musées d'art sacré", "Pourquoi le silence se fait-il naturellement sans qu'aucun gardien n'intervienne ?", ["Hauteur sous plafond", "Écho monumental", "Pression normative implicite"], "Le volume architectural peut-il imposer une discipline auditive spontanée ?", "Église / Temple"),
    ("L'hypothèse du packaging épuré des produits haut de gamme", "Compare une boîte de smartphone premium à un jouet bon marché surchargé d'inscriptions.", ["Minimalisme = Confiance", "Rareté = Valeur", "Silence visuel"], "Le luxe se définit-il par la soustraction de bruit publicitaire ?", "Boutique de design"),
    ("La stratégie de la musique d'ambiance à tempo lent", "Observe le type de musique diffusée dans un magasin de vêtements chic.", ["60 battements par minute", "Pas de paroles agressives", "Baisse du rythme cardiaque"], "La musique sert-elle à ralentir la cadence de marche des clients ?", "Magasin"),
    ("L'intention derrière les miroirs dans les ascenseurs", "Pourquoi installe-t-on systématiquement des miroirs dans les cabines d'ascenseur ?", ["Sensation d'espace agrandi", "Occupation de l'attention par son propre reflet", "Baisse perçue du temps de trajet"], "Le miroir est-il un anesthésiant de l'impatience ?", "Ascenseur"),
    ("La logique d'agencement des applications sur un smartphone neuf", "Regarde quelles applications sont pré-installées sur la page d'accueil d'usine.", ["Services payants du fabricant", "Réseaux partenaires", "Applications à forte rétention"], "L'écran d'accueil par défaut est-il le mètre carré le plus cher du monde ?", "Téléphone"),
    ("L'hypothèse des zones piétonnes pavées plutôt que goudronnées", "Pourquoi pose-t-on des pavés irréguliers dans les centres-villes historiques ?", ["Ralentissement des véhicules", "Sensibilité tactile sous la semelle", "Caractère patrimonial"], "La texture du sol change-t-elle notre façon d'habiter la ville ?", "Centre historique"),
    ("L'intention du bip sonore aux barrières de péage ou métro", "Pourquoi le signal sonore est-il distinctement aigu et court ?", ["Confirmation sans regarder l'écran", "Libération du flux", "Clôture de la transaction"], "Le feedback sonore remplace-t-il la vérification visuelle ?", "Péage / Portillon"),
    ("La logique des escaliers monumentaux devant les palais de justice", "Pourquoi doit-on gravir vingt marches pour entrer dans un bâtiment institutionnel ?", ["Élévation symbolique", "Effort physique requis", "Impression de petitesse"], "L'escalier prépare-t-il psychologiquement à la soumission à l'institution ?", "Tribunal / Mairie"),
    ("L'hypothèse de la lumière jaune chaude dans les cafés", "Pourquoi les cafés évitent-ils les néons blancs froids des bureaux ?", ["Simulation du feu de camp", "Sécrétion de mélatonine", "Sentiment de cocon protecteur"], "La température de couleur commande-t-elle notre sentiment de sécurité ?", "Café"),
    ("L'intention des odeurs diffusées dans les hôtels de luxe", "Remarque le parfum d'ambiance discret à la réception d'un grand hôtel.", ["Signature olfactive unique", "Mémoire émotionnelle immédiate", "Sensation de propreté absolue"], "L'odorat est-il le sens le plus direct pour ancrer un souvenir ?", "Hôtel"),
    ("La logique des notifications Push 'X a aimé votre publication'", "Pourquoi la plateforme t'avertit-elle d'un like plutôt que d'attendre que tu viennes voir ?", ["Déclencheur externe", "Validation sociale instantanée", "Réactivation du réflexe"], "La notification est-elle une invitation ou un hameçon cognitif ?", "Réseau social"),
    ("L'hypothèse des bureaux assis-debout dans les entreprises modernes", "Pourquoi remplace-t-on les chaises ergonomiques par des postes modulables ?", ["Changement postural = vigilance accrue", "Baisse de la sédentarité", "Image d'agilité"], "Le mouvement physique est-il le carburant sous-estimé de l'attention ?", "Poste de travail"),
    ("L'intention derrière les formats courts (Reels, TikTok)", "Pourquoi la vidéo fait-elle 15 secondes plutôt que 5 minutes ?", ["Élimination de la friction d'engagement", "Récompense variable accélérée", "Baisse de l'effort attentionnel"], "Le format court est-il optimisé pour la capture sans réflexion ?", "Application"),
    ("La logique des sièges inclinés et durs dans les fast-foods", "Pourquoi les chaises de restauration rapide sont-elles moins confortables que celles des brasseries ?", ["Rotation rapide des tables", "Consommation express", "Éviter que les gens s'attardent"], "Le mobilier peut-il être programmé pour écourter la présence ?", "Fast-food"),
    ("L'hypothèse des cours de récréation avec zones de calme végétalisées", "Pourquoi remplace-t-on l'asphalte noir par des copeaux de bois et des bosquets ?", ["Baisse des conflits et cris", "Apaisement sensoriel", "Diversification des jeux"], "L'environnement naturel pacifie-t-il les interactions spontanées ?", "Espace scolaire"),
    ("L'intention des pastilles rouges de notification", "Pourquoi le rouge a-t-il été choisi pour les badges plutôt que le bleu ou le vert ?", ["Couleur du danger et de l'urgence", "Capture attentionnelle involontaire", "Biais de complétion à effacer"], "Le rouge est-il une alarme biologique détournée pour le profit ?", "Interface"),
    ("La logique des chariots de supermarché surdimensionnés", "Pourquoi les caddies modernes sont-ils deux fois plus grands qu'il y a quarante ans ?", ["Effet de vide perçu", "Tendance à remplir l'espace disponible", "Baisse de la conscience de volume"], "Le contenant dicte-t-il la taille du contenu ?", "Magasin"),
    ("L'hypothèse de l'isolation phonique dans les voitures modernes", "Pourquoi les constructeurs éliminent-ils tout bruit de moteur dans l'habitacle ?", ["Création d'un salon roulant", "Baisse de la sensation de vitesse", "Augmentation du sentiment de toute-puissance"], "Le silence mécanique déconnecte-t-il le conducteur de la réalité physique ?", "Voiture"),
    ("L'intention des boutons 'Commander en 1 clic'", "Pourquoi supprime-t-on l'étape du panier et de la récapitulation ?", ["Élimination du remords de l'acheteur", "Zéro temps de réflexion", "Impulsion pure"], "La friction d'achat est-elle la seule gardienne de notre budget ?", "Site e-commerce"),
    ("La logique des bibliothèques ouvertes 24h/24", "Pourquoi l'accès nocturne est-il plébiscité par certains profils d'étudiants ?", ["Absence totale de sollicitations extérieures", "Sanctuaire de silence absolu", "Solidarité de l'effort nocturne"], "La nuit offre-t-elle la dernière forteresse contre la dispersion moderne ?", "Campus universitaire")
]

for title, mission_text, cues, reflection, context in templates:
    diff = 1 if m_id <= 25 else (2 if m_id <= 50 else (3 if m_id <= 75 else (4 if m_id <= 100 else 5)))
    cat = categories[diff - 1][1]
    missions.append({
        "id": m_id,
        "title": f"MISSION {m_id:03d} — {title.upper()}",
        "category": cat,
        "mission": mission_text,
        "cues": cues,
        "reflection": reflection,
        "difficulty": diff,
        "recommendedContext": context
    })
    m_id += 1

with open(os.path.join(CONTENT, "missions.json"), "w", encoding="utf-8") as f:
    json.dump(missions, f, ensure_ascii=False, indent=2)

print(f"Generated missions.json ({len(missions)} items across 5 levels)")
