#!/usr/bin/env python3
"""Final rounding pass: one short paragraph for entries still under target."""

from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CONTENT = os.path.join(ROOT, "Reboot", "Content")

READINGS2 = {
22: ["Ce que cette idée change en pratique : avant de se plaindre de sa propre dispersion, on peut examiner les cadres qui la rendent possible. La question n'est plus « pourquoi suis-je faible ? » mais « quels cadres ai-je acceptés sans les choisir ? ». Les cadres du flux — défilement infini, notifications, disponibilité permanente — n'ont jamais été choisis ; ils ont été hérités. Les cadres du protocole, eux, sont choisis. Et cette différence est la liberté : non pas vivre sans cadres, mais habiter ceux que l'on a choisis."],
23: ["Un point d'équilibre : la lenteur ne doit pas devenir une posture. La lenteur qui se contemple, qui refuse toute vitesse, devient aussi une prison que la vitesse. La compétence n'est pas d'être toujours lent ; c'est de savoir choisir le tempo selon l'activité. Répondre vite à une urgence réelle, lire lentement un texte qui compte, marcher sans but quand le corps le demande : chaque tempo a sa place. L'entraînement à la lenteur n'est pas une condamnation de la vitesse ; c'est une restauration du choix. Celui qui ne peut que ralentir n'est pas plus libre que celui qui ne peut qu'accélérer."],
24: ["Il y a une dernière observation sur les déclencheurs : ils sont souvent liés à des états internes, pas seulement à des objets. La fatigue, l'ennui, l'anxiété, la faim : ces états abaissent la barrière et rendent le réflexe plus fort. Un même téléphone déclenche plus de vérifications quand on est fatigué que quand on est reposé. Cette observation a une conséquence pratique : gérer le réflexe, c'est aussi gérer les états. Dormir, manger, prendre l'air, reconnaître sa fatigue : ce sont des réglages indirects du conditionnement. La vigilance n'est pas seulement une affaire de réflexes ; c'est une affaire de conditions internes."],
25: ["Un exemple concret du transfert : un projet de plusieurs mois. Il commence avec enthousiasme, traverse des semaines sans intérêt visible, et n'aboutit qu'à la fin. La capacité de le mener à bien ne vient pas de l'intensité de l'enthousiasme ; elle vient de la capacité de rester pendant les semaines sans intérêt. Les sessions du protocole sont de petits projets : une durée, une traversée, une fin. Chaque session tenue enseigne au niveau de l'heure ce que le projet demande au niveau des mois : la nouveauté passe, le milieu résiste, et la fin vient à ceux qui restent."],
26: ["Une dernière précision : la présence n'est pas une performance. On ne devient pas présent en se surveillant ; on devient présent en s'orientant. La différence est subtile mais décisive : la surveillance ajoute une attention de contrôle, qui encombre la scène ; l'orientation simplifie la scène, qui se remplit de l'objet. Les sessions du protocole sont orientées — une tâche, une durée — et cette orientation fait le travail que la surveillance ne fait pas. La présence n'est pas le résultat d'un effort de présence ; c'est le résultat d'une attention donnée à autre chose."],
27: ["Une application précise : les repas. Un repas pris avec un écran est un repas où l'attention conjointe est divisée ; un repas sans écran est un repas où la présence peut circuler. Ce choix ne demande aucune compétence particulière ; il demande une règle. La règle peut être simple : pas d'écran à table. Cette règle, appliquée régulièrement, restaure des centaines de moments d'attention conjointe par an. Les grandes transformations de l'attention ne passent pas seulement par les sessions ; elles passent par les règles qui protègent les moments ordinaires."],
28: ["Il y a un paradoxe à accepter : lire moins peut être lire plus. Celui qui lit dix textes par survol possède moins que celui qui lit un texte par semaine et le reconstruit. La quantité lue n'est pas une mesure de lecture ; c'est une mesure d'activité. La possession — ce que l'on peut reformuler, appliquer, enseigner — est la seule mesure qui compte. L'entraînement à la lecture active est un échange assumé : moins de titres, plus de possession. Et la possession s'accumule d'une manière que le survol ne connaît pas : chaque idée possédée en prépare une autre."],
29: ["Il faut aussi parler des interruptions positives : toutes ne sont pas des pertes. Une interruption qui apporte une information vitale, une demande urgente réelle, un imprévu qui change le cours : ces interruptions sont des événements, pas des parasites. La compétence n'est pas de tout refuser ; c'est de trier. Le tri rapide — est-ce une urgence réelle ou une saillance ? — se fait en une seconde, et il décide de la réponse. L'entraînement ne rend pas insensible aux interruptions ; il rend le tri plus rapide et la réponse plus juste. Les vraies urgences passent ; le bruit reste dehors."],
30: ["Il y a aussi une dimension collective de l'observation : elle change la conversation. Celui qui observe a des choses à dire que celui qui consomme n'a pas : des détails vus, des questions posées au réel, des récits de première main. L'observation nourrit la parole d'une matière que le flux ne fournit pas. Dans un monde où tout le monde répète les mêmes contenus, l'observateur apporte du neuf — non pas du nouveau contenu, mais du réel. Cette rareté est précieuse, et elle se construit par un entraînement simple : regarder assez longtemps pour avoir quelque chose à dire."],
31: ["Il y a une conséquence sur l'échec : si l'attention est une compétence, l'échec est un diagnostic, pas une identité. Une session difficile dit quelque chose sur les conditions, pas sur la valeur. Le langage change : « je suis nul » devient « la durée était trop longue pour ce soir, dans ce bruit, avec cette fatigue ». Ce langage est moins dramatique et plus utile. Il permet d'ajuster : réduire, déplacer, préparer. La pratique devient une conversation avec ses propres conditions au lieu d'un procès contre soi. Et cette conversation est infiniment plus productive."],
32: ["Une objection fréquente : la qualité, c'est bien, mais il faut quand même du volume pour progresser. La réponse est dans la nature du volume : une heure de présence intermittente contient moins de pratique qu'une demi-heure de présence réelle. Le volume de présence réelle est ce qui compte, et il se construit par des sessions complètes, pas par des heures fragmentées. Le protocole choisit donc des durées modestes et complètes : dix minutes entières valent mieux que quarante minutes interrompues. À mesure que la capacité grandit, le volume suit naturellement : on allonge des sessions complètes, on n'accumule pas des fragments."],
33: ["Une application dans la vie courante : les moments d'attente. Une file, un transport, une pause : le corps y a souvent une posture de dispersion — épaules levées, regard errant, téléphone en main. Choisir une posture stable — s'asseoir droit, poser les pieds, ralentir la respiration — transforme l'attente en présence. Le corps est le premier instrument de l'attention, et il est toujours disponible. Les sessions l'apprennent dans un cadre ; la vie l'applique dans les interstices. Cette application est peut-être la plus accessible de tout le protocole : elle ne demande ni temps, ni lieu, ni matériel — seulement la décision de laisser le corps participer."],
34: ["Il y a une règle de mesure pour ce compromis : la proportion. Combien de tes heures sont-elles du temps réel subi, et combien sont-elles du temps choisi ? La question n'est pas d'atteindre zéro heure réelle ; c'est de connaître la proportion et de la faire évoluer. Une journée avec une majorité de temps choisi est une journée vécue ; une journée avec une majorité de temps subi est une journée traversée. Le protocole ne mesure pas le temps réel pour le supprimer ; il le mesure pour l'équilibrer. Et l'équilibre se construit par des décisions simples : fenêtres de consultation, moments de présence, sessions protégées."],
35: ["Il y a une découverte à faire dans cette pratique : ce que l'on fuyait est souvent moins l'objet que la sensation de rester. Rester avec une tâche difficile, c'est rester avec soi ; et rester avec soi n'est pas toujours confortable. Les distractions sont des sorties de cette confrontation. Les sessions sont des exercices de confrontation choisie : rester avec la tâche, rester avec l'inconfort, rester avec la durée. À force, la confrontation perd son pouvoir : on découvre que l'on peut être avec soi sans fuir. Cette découverte est peut-être le plus grand bénéfice de l'entraînement — plus grand que la productivité, plus grand que la concentration : la capacité d'être avec soi."],
36: ["Il y a une dernière architecture à considérer : celle du début de journée. Les premières minutes après le réveil règlent le régime de la journée entière. Une journée commencée dans le flux est une journée où le flux est la référence ; une journée commencée par un moment calme est une journée où le calme existe. Cette architecture est la plus simple et la plus puissante : elle ne demande qu'une décision, prise la veille ou au réveil. Le protocole peut l'organiser en plaçant les sessions tôt, mais l'essentiel est la règle : avant d'ouvrir le monde, s'ouvrir à soi."],
37: ["Une application personnelle de cette histoire : se choisir une pratique, pas seulement une opinion. Les opinions sur les écrans sont nombreuses et polarisées ; les pratiques sont rares. Une pratique — lire un texte long par semaine, une session par jour, un repas sans écran — est une réponse concrète à une question abstraite. Elle ne résout pas le débat, mais elle transforme le rapport personnel à la technologie. Et les pratiques, à la différence des opinions, se transmettent : un enfant qui voit un parent lire lentement apprend autre chose qu'un enfant qui entend des discours. La pratique est la seule pédagogie qui ne ment pas."],
40: ["Il faut ajouter une remarque sur la répétition espacée, qui est le complément naturel de la reconstruction. Une trace se consolide mieux quand elle est récupérée plusieurs fois, à des intervalles croissants : le lendemain, puis trois jours après, puis une semaine. Le protocole produit cette répétition organiquement : les lectures reviennent sous d'autres formes, les idées se retrouvent dans les restitutions, les jours passent et la matière revient. La répétition espacée n'est pas une technique à ajouter ; c'est une propriété de la régularité. Les sessions espacées font le travail de consolidation que la concentration seule ne fait pas."],
41: ["Une dernière précision sur les habitudes d'attention : elles sont fragiles par nature, et cette fragilité est une information, pas une faiblesse. Une habitude qui s'interrompt à la première contrariété n'était pas une habitude ; c'était une performance. La vraie habitude a une élasticité : elle se déforme sous la pression et revient quand la pression cesse. Cette élasticité se construit par la répétition des retours : chaque reprise après une interruption renforce la capacité de reprise. C'est la règle du protocole — tu reprends — appliquée au niveau de l'habitude elle-même. L'habitude élastique survit aux voyages, aux urgences, aux semaines chargées ; l'habitude rigide se casse."],
43: ["Une considération finale : la technique et l'usage forment une boucle. Les outils façonnent les usages, et les usages façonnent les attentes, et les attentes orientent la conception des outils suivants. Cette boucle n'est pas fatale ; elle est le lieu de l'action. Chaque usage choisi — fermer, ralentir, lire — est un signal envoyé au système : voilà ce que nous voulons faire. Les concepteurs répondent aux usages réels plus qu'aux discours. En ce sens, la maîtrise individuelle n'est pas seulement personnelle ; elle est un vote. Chaque session, chaque lecture profonde, chaque notification ignorée est un vote pour une autre technologie."],
44: ["Une dernière question de méthode : comment mesurer le retour sur investissement de l'attention ? La réponse la plus simple est la trace : les sessions complétées, les restitutions produites, les capacités observées. Mais il existe une mesure plus intime, que les chiffres ne capturent pas : la sensation de présence. Une journée où l'on a été réellement présent laisse une trace subjective — la journée a eu de l'épaisseur. Cette sensation n'est pas mesurable au compteur, mais elle est reconnaissable. L'entraînement à l'attention produit les deux mesures : des données visibles, et une texture vécue. Les deux sont réelles ; les deux comptent."],
45: ["Il y a une conséquence pour l'organisation personnelle : les bascules se réduisent en regroupant. Traiter les messages en deux fenêtres par jour, plutôt qu'en continu, réduit le nombre de bascules sans réduire le nombre de réponses. Lire un texte en un bloc, plutôt qu'en fragments, réduit les coûts de reprise. Ces regroupements ne sont pas des contraintes ; ce sont des économies. Ils reconnaissent que le coût n'est pas dans l'activité, mais dans la bascule. Et la bascule est la variable que l'on peut réduire le plus facilement : il suffit de grouper, de fermer, de décider des fenêtres."],
46: ["Il y a un exercice pratique pour entraîner la patience : le retard volontaire. Avant de répondre, d'agir, de conclure, attendre un temps défini — dix secondes, une minute, une heure selon l'enjeu. Ce retard n'est pas une hésitation ; c'est une méthode. Il laisse à la pensée le temps de passer de la réaction à la réponse. Les sessions du protocole sont des retards volontaires de plus grande ampleur : rester avec une tâche au-delà de la première réaction, rester avec un texte au-delà de la première lecture. La patience se construit par ces retards répétés : elle est la capacité de ne pas conclure avant que la matière ait livré ce qu'elle contient."],
48: ["Il y a une nuance sur la lumière et les écrans : le soir, la lumière bleue et la stimulation retiennent l'éveil. Ce n'est pas une condamnation des écrans ; c'est une donnée d'hygiène. Une heure de lumière forte avant le coucher retarde la mélatonine et déplace le sommeil. Les règles pratiques sont simples : baisser la lumière le soir, éviter les contenus stimulants avant de dormir, donner à la nuit un rituel de descente. Ces règles ne font pas partie des sessions, mais elles en protègent les bénéfices : une session construite la journée est consolidée la nuit, et la consolidation est la moitié du travail. Négliger la nuit, c'est perdre la moitié de l'entraînement."],
49: ["Il faut enfin considérer l'attention des autres : nous reconstruisons aussi le monde des personnes avec qui nous vivons. Quand nous écoutons, nous participons à leur reconstruction ; quand nous sommes absents, nous la laissons seule. L'attention n'est donc pas seulement un instrument personnel ; c'est une responsabilité partagée. Les moments où l'on donne son attention entière — à une conversation, à un récit, à une difficulté — sont des moments où l'on aide quelqu'un à construire son monde. Cette dimension transforme l'entraînement : on ne s'entraîne pas seulement pour soi, mais pour la qualité des mondes communs. Et cette perspective donne aux sessions une portée que les statistiques ne montrent pas."],
}

LEARNINGS2 = {
2: ["Un dernier point sur la déconstruction : elle ne consiste pas à se priver du téléphone, mais à changer sa place dans la journée. Le téléphone reste un outil utile ; le problème est sa position de réflexe permanent. La déconstruction transforme un geste automatique en action choisie : on consulte à des moments décidés, pour des raisons précises, avec une fin claire. Cette transformation ne demande pas de volonté héroïque ; elle demande un aménagement — fenêtres de consultation, téléphone hors de portée, notifications réduites. Le réflexe cède la place à une pratique, et la pratique, elle, peut être choisie."],
3: ["Il y a une application précise à l'entraînement : la session comme expérience contrôlée. On choisit une variable — la durée, le moment, l'environnement — et l'on observe le résultat. Cette méthode transforme la pratique en science personnelle : chaque semaine apporte une donnée, chaque donnée affine le réglage. Elle protège aussi des conclusions hâtives : une session difficile n'est pas un verdict, c'est un résultat d'expérience avec des conditions à examiner. Le protocole est ainsi une école de méthode : apprendre à tester, à observer, à corriger — plutôt qu'à affirmer, à conclure et à abandonner."],
4: ["Il y a une application directe au protocole : le coût d'opportunité des sessions elles-mêmes. Une session de vingt minutes a un coût — vingt minutes que l'on ne passe pas ailleurs. Elle doit donc être placée là où sa valeur est maximale : au moment où l'attention est la plus haute, quand l'alternative est la moins précieuse. Cette logique explique pourquoi le moment de la session compte autant que son contenu. Une session mal placée est une dépense sans retour ; une session bien placée est un investissement. La planification n'est pas une contrainte ; c'est la forme pratique du coût d'opportunité."],
5: ["Il y a une objection à examiner : aménager l'environnement ne revient-il pas à fuir sa propre faiblesse ? La réponse est l'inverse : aménager, c'est reconnaître la mécanique et la prendre au sérieux. Celui qui s'en remet uniquement à la volonté traite la faiblesse comme une faute ; celui qui aménage la traite comme une donnée. L'aménagement n'élimine pas la responsabilité ; il la déplace vers la décision anticipée. Décider à l'avance, dans le calme, ce que l'on fera dans la tentation : c'est une forme supérieure de volonté, qui ne s'épuise pas parce qu'elle a déjà décidé."],
6: ["Il y a une leçon de prudence pour les environnements : ils adaptent aussi. Un environnement qui change constamment — nouvelles applications, nouvelles notifications, nouveaux contenus — maintient le cerveau dans un état d'adaptation permanente. Cette adaptation a un coût : elle consomme la ressource que l'entraînement voudrait protéger. La stabilité de l'environnement est donc un allié de la plasticité dirigée : moins de nouveautés à intégrer, plus de répétition choisie. Aménager, c'est aussi stabiliser : garder les mêmes outils, les mêmes moments, les mêmes règles, assez longtemps pour que l'adaptation travaille dans la bonne direction."],
7: ["Il y a un piège dans la lecture des boucles : le désir de tout contrôler. On découvre une boucle de distraction et l'on veut la supprimer entièrement ; on découvre une boucle utile et l'on veut la forcer. Cette ambition est contre-productive : les boucles sont des circuits, pas des interrupteurs. Elles se modifient par petits réglages, et le réglage le plus efficace est souvent le plus simple — changer un déclencheur, supprimer une récompense, ajouter un délai. La patience dans le réglage est aussi importante que la justesse du diagnostic. Une boucle bien comprise se réaménage ; une boucle mal comprise se combat, et la lutte épuise."],
9: ["Une application concrète de la saillance : les modes de concentration des appareils. Ils réduisent les saillances — notifications, animations, badges — pendant une durée définie. Leur efficacité ne vient pas de la volonté qu'ils exigent, mais de l'absence d'invitations qu'ils créent. L'attention n'a plus à refuser ; elle n'a rien à attraper. Cette architecture est le même principe que les sessions du protocole, appliqué au niveau de l'outil : réduire les saillances pour libérer la ressource. Aménager son environnement, c'est multiplier ces dispositifs simples : moins de points rouges, moins de sons, moins d'animations — et plus d'attention disponible."],
10: ["Il y a une précision sur la reformulation orale : elle est plus exigeante encore que la reformulation écrite. À l'écrit, on peut revenir, corriger, raturer ; à l'oral, la phrase se construit en direct, et les trous apparaissent immédiatement. Cette exigence est un avantage : l'oral est un test de compréhension plus sévère et plus rapide. Le protocole l'utilise dans le mode EXPLAIN : enseigner, c'est reformuler à voix haute, pour quelqu'un, sans filet. Cette pratique développe une compétence que l'écrit seul ne donne pas : la capacité de penser debout, de construire une explication en direct, de trouver les mots justes sous la pression du temps."],
11: ["Il y a une application à la planification : les bilans périodiques. Une fois par semaine, regarder la trace sans jugement immédiat — juste lire la série : les durées, les retours, les tendances. Ce bilan périodique est un contre-biais : il voit ce que l'humeur du jour ne voit pas. Il révèle des tendances réelles que les impressions contredisent : on croyait stagner, la série montait ; on croyait progresser, la série montrait des trous. Le bilan hebdomadaire est la discipline du biais : accepter de regarder les données avant de conclure, et laisser les données corriger les croyances."],
13: ["Il y a une application concrète de cette philosophie du temps : les rituels. Un rituel est un moment où le temps présent est intentionnellement habité — un café sans écran, une lecture courte, une marche sans but. Les rituels ne sont pas des décorations ; ce sont des enclaves de présence dans des journées de flux. Ils sont courts, mais ils sont entiers. Leur répétition construit une mémoire du présent : on se souvient des rituels, parce qu'on y était. L'entraînement à l'attention peut commencer par là : non pas par une session, mais par un rituel de cinq minutes, tenu chaque jour, où l'on est simplement là. Le reste suit."],
14: ["Il y a une nuance importante : la réhabituation n'est pas un retour à un état « naturel » de calme. Elle est un réglage nouveau, adapté à un environnement qui restera stimulant. La tolérance au vide ne supprime pas la sensibilité au flux ; elle l'équilibre. Une personne réhabituée peut encore apprécier une application, une série, un contenu — mais elle n'en a plus besoin pour exister. Cette différence est la vraie mesure de la réhabituation : non pas l'absence de plaisir dans le flux, mais l'absence de dépendance. Le plaisir reste ; la nécessité disparaît. Et c'est cette disparition qui change la vie : les moments vides redeviennent habitables."],
19: ["Il y a une objection à anticiper : l'intention ne peut-elle pas devenir rigide, et l'action perdre sa spontanéité ? C'est possible, si l'intention est confondue avec le contrôle. Mais l'intention bien comprise laisse de la place à la découverte : on fixe une direction, et l'on reste ouvert à ce que le chemin révèle. Une session avec intention n'est pas une session verrouillée à l'avance ; c'est une session orientée, qui peut surprendre. La spontanéité n'est pas l'absence de direction ; c'est la liberté à l'intérieur d'une direction. L'entraînement vise cette combinaison : une direction claire, et une attention ouverte à ce qui arrive."],
20: ["Il y a une application précise à la lecture : lire en écoutant de la musique avec paroles est une combinaison coûteuse pour la compréhension ; lire dans le silence en est une sans coût. Ces différences sont faciles à tester : comparer la compréhension d'un texte dans les deux conditions. La plupart des gens constatent une différence nette, et cette constatation suffit à changer les habitudes : on réserve le silence aux lectures qui comptent. L'entraînement à l'attention est aussi un apprentissage des conditions : savoir ce qui coûte, savoir ce qui libère, et choisir ses combinaisons en connaissance de cause. Cette connaissance est une compétence en soi."],
21: ["Il y a une application à la comparaison avec les autres : elle est presque toujours un échantillon biaisé. On se compare à ceux qui montrent leurs réussites et cachent leurs échecs ; on oublie que leurs conditions ne sont pas les nôtres. Cette comparaison produit des généralisations hâtives — « tout le monde y arrive, pas moi » — qui ne reposent sur aucune donnée solide. La trace protège de cette erreur en fournissant le seul échantillon que l'on puisse connaître vraiment : le sien. La question n'est pas « où sont les autres ? » ; elle est « où est ma pente, et est-ce qu'elle va dans le bon sens ? ». La réponse est dans les données, pas dans les vitrines."],
23: ["Il y a une application de la phénoménologie au diagnostic : les sensations sont des instruments. Une session où l'effort est constant peut signaler une durée trop longue ; une session où l'ennui domine peut signaler une tâche trop facile ; une session où la fluidité apparaît signale le bon réglage. Ces sensations ne sont pas des preuves, mais elles sont des indices. Les noter — dans la trace, dans un carnet — permet de repérer des régularités que les chiffres seuls ne montrent pas. L'entraînement sérieux écoute les deux langages : celui des données et celui du corps. Le premier mesure, le second oriente."],
24: ["Il y a une précision sur le rôle de l'effort dans l'absorption : l'effort initial est presque toujours présent. Même dans les activités aimées, l'entrée demande un démarrage : quelques minutes où l'attention hésite, où l'esprit propose autre chose. L'absorption vient après ce seuil. Ceux qui croient que l'absorption doit être immédiate abandonnent au seuil ; ceux qui connaissent la structure — un seuil, puis la fluidité — traversent le seuil et attendent la fluidité. Cette connaissance change la pratique : au lieu de juger la session sur ses premières minutes, on la juge sur sa trajectoire. Le seuil n'est pas un échec ; c'est la porte."],
25: ["Il y a une question de durée des incitations réelles : elles sont lentes, et cette lenteur est une protection. Les récompenses factices agissent vite et s'épuisent vite ; les récompenses réelles agissent lentement et durent. La capacité qui grandit, la trace qui s'accumule, la tendance qui monte : ces récompenses ne donnent pas le frisson du badge, mais elles donnent la satisfaction de la construction. L'entraînement à l'attention apprend à habiter cette temporalité : accepter que les vraies récompenses viennent en différé, et ne pas échanger cette lenteur contre des signaux brillants et vides. La patience devant les récompenses réelles est une compétence de motivation."],
26: ["Il y a une application à l'enseignement : expliquer à quelqu'un est le meilleur test de sa propre patience épistémique. Devant une question, on découvre ses propres trous, et l'on doit accepter de ne pas savoir, chercher, reformuler. Cette expérience est humiliante et féconde. Le mode EXPLAIN organise cette traversée : on apprend, on ferme, on enseigne, et les questions de l'auditeur imaginaire révèlent les manques. L'humiliation de ne pas savoir expliquer devient une information : voilà ce qui reste à comprendre. La patience épistémique transforme cette humiliation en programme de travail, au lieu d'en faire une raison de se taire."],
28: ["Il y a une application à la consommation d'actualités : la plupart des flux d'actualités sont de la stimulation déguisée en information. Les titres sont conçus pour attirer, pas pour informer ; les mises à jour répètent ce qui ne change rien ; l'urgence est fabriquée. Cette reconnaissance ne conduit pas à ignorer le monde ; elle conduit à choisir ses sources : quelques sources fiables, consultées à des moments décidés, au lieu d'un flux permanent. L'entraînement à l'information réelle est donc un entraînement au choix des sources et des moments. Il ne dit pas quoi penser ; il dit comment recevoir : moins de bruit, plus de signal, et des décisions mieux éclairées."],
29: ["Il y a une application au contenu du protocole : la progression des modes est une exploration bornée. Les phases alternent les disciplines — concentration, lecture, apprentissage, vide, observation — et cette alternance explore les différentes facettes de l'attention. Mais chaque phase stabilise aussi un mode : la phase I travaille le court et le simple, la phase II allonge, la phase III approfondit. L'alternance explore, la progression exploite. Cette double structure est le dosage du protocole : assez de variété pour ne pas s'ennuyer, assez de stabilité pour construire. L'équilibre entre explorer et exploiter n'est pas un concept ; c'est le calendrier lui-même."],
33: ["Il y a une application à la lecture de la trace : la variance y est visible. Une trace régulière — des sessions proches en durée, des trous courts — est une trace à variance faible ; une trace en dents de scie — des sommets et des abandons — est une trace à variance forte. Lire sa trace, c'est lire sa variance, et lire sa variance, c'est connaître la vraie nature de sa pratique : régulière ou spasmodique. Cette lecture n'est pas un jugement ; c'est un diagnostic. Et le diagnostic oriente le réglage : si la variance est forte, la priorité n'est pas l'intensité, c'est la régularité. La trace ne dit pas si l'on est bon ; elle dit ce qu'il faut régler."],
34: ["Il y a une application concrète du temps vécu au repos : le repos n'est pas le remplissage. Un repos de qualité — une pause sans écran, une promenade, un moment de silence — est un temps vécu qui régénère ; un repos avec flux est souvent un temps traversé qui fatigue. Cette distinction change la gestion des pauses : au lieu de remplir les interstices, on les habite. Le protocole organise cette habitation dans le mode NOTHING, mais la compétence s'applique à toutes les pauses : la qualité du repos dépend de la présence, pas de l'activité. Apprendre à se reposer vraiment, c'est apprendre à être présent même quand l'on ne produit rien."],
}

def load(name):
    with open(os.path.join(CONTENT, f"{name}.json")) as f:
        return json.load(f)

def save(name, data):
    with open(os.path.join(CONTENT, f"{name}.json"), "w") as f:
        f.write("[\n")
        f.write(",\n".join(json.dumps(e, ensure_ascii=False) for e in data))
        f.write("\n]\n")

def main():
    readings = load("readings")
    for entry in readings:
        extra = READINGS2.get(entry["id"])
        if extra:
            entry["text"] = entry["text"] + "\n\n" + "\n\n".join(extra)
    save("readings", readings)
    learnings = load("learnings")
    for entry in learnings:
        extra = LEARNINGS2.get(entry["id"])
        if extra:
            entry["text"] = entry["text"] + "\n\n" + "\n\n".join(extra)
    save("learnings", learnings)
    print("round 2 applied")

if __name__ == "__main__":
    main()
