#!/usr/bin/env python3
"""Appends authored extension paragraphs to bundled content so each entry
meets its declared word range without filler. Each paragraph continues the
argument of the original text."""

from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CONTENT = os.path.join(ROOT, "Reboot", "Content")

READINGS_EXT = {
1: [
 "Il y a une conséquence pratique à cette vision : le contrôle de l'attention n'est pas une affaire de grande décision, mais de petites transactions refusées. La journée ne se gagne pas en un geste héroïque ; elle se gagne dans les trente moments où l'on choisit de ne pas suivre la pente. Chaque refus est discret, presque invisible, mais il s'additionne. C'est ce que les sessions du protocole répètent : non pas de grandes batailles, mais une série de retours.",
 "Une dernière précision : il ne faut pas confondre l'entraînement avec la dureté envers soi-même. Refuser une transaction ne veut pas dire se mépriser quand on cède. Le mécanisme fonctionne par renforcement, pas par punition. Chaque retour est un renforcement ; chaque culpabilité inutile est une transaction de plus, cette fois contre soi. La pratique sérieuse est une pratique claire : on observe, on revient, on continue."],
2: [
 "Le coût du changement se paie aussi dans la qualité des transitions. Quand on passe d'une tâche à l'autre en continu, on perd la sensation de terminer : rien ne se clôt, tout reste ouvert, et l'esprit porte en permanence des choses inachevées. Cette charge invisible est une des sources de la fatigue moderne. Terminer une chose, même petite, produit une libération que le changement permanent ne connaît jamais.",
 "L'entraînement peut commencer par un exercice modeste : choisir une tâche, annoncer sa fin, et ne pas la quitter avant d'avoir atteint ce point. La fin peut être un signal simple — un paragraphe achevé, une question répondue, un état enregistré. Ce qui compte, c'est de restaurer la sensation de complétude. Les sessions du protocole sont des unités closes : elles commencent, elles finissent, et la fin appartient au pratiquant."],
3: [
 "La distraction a aussi une dimension sociale qu'il ne faut pas négliger. Une partie des vérifications ne répond pas à un besoin personnel, mais à une inquiétude relationnelle : on craint d'être absent, de manquer une demande, de ne pas répondre assez vite. Cette crainte est légitime, mais elle est souvent disproportionnée. L'examen des distractions devrait donc inclure une question : cette urgence vient-elle de la chose, ou de ma peur de décevoir ?",
 "Poser cette question ne résout pas tout, mais elle change le rapport au geste. On cesse de subir une pulsion indistincte ; on commence à voir une mécanique précise, avec ses craintes et ses attentes. Et ce qui est vu peut être négocié : répondre plus tard, prévenir, choisir ses moments. La discipline n'est pas l'ennemie de la relation ; la discipline est ce qui permet de revenir à la relation avec une attention entière."],
4: [
 "La rapidité du retour a une conséquence sur la façon de mesurer les sessions. Un compteur qui ne noterait que le nombre de changements raterait l'essentiel : le délai de retour. Deux sessions avec le même nombre de changements peuvent être très différentes — l'une où l'on s'évade plusieurs minutes, l'autre où l'on revient en quelques secondes. C'est le retour qui s'entraîne, pas l'absence de départs.",
 "Une image peut aider : l'attention est comme un bateau qui dérive. Tous les bateaux dérivent ; la différence est dans la vitesse à laquelle on remarque la dérive et la correction qu'on applique. Le marin entraîné ne supprime pas le vent ; il corrige plus vite. Chaque session est une navigation : le vent soufflera, la dérive viendra, et la compétence se mesure dans la correction."],
5: [
 "L'environnement agit aussi par ce qu'il ne contient pas. Un espace vide de propositions est un espace où l'attention n'a rien à refuser ; mais un espace trop vide peut devenir une prison, où l'esprit cherche du stimulus au lieu de travailler. L'équilibre n'est pas l'ascèse ; c'est la pauvreté choisie : assez de ressources pour la tâche, rien de plus.",
 "Cette pauvreté se construit en deux temps. D'abord, on retire ce qui propose : notifications, onglets, appareils. Ensuite, on ajoute ce qui soutient : une page, un crayon, une lumière stable. Le résultat n'est pas une table vide ; c'est une table préparée pour une seule chose. Et cette préparation, répétée chaque jour, devient une entrée en matière : le geste d'arranger l'espace annonce au corps et à l'esprit que la session commence."],
6: [
 "Il y a une différence entre lire pour se reposer et lire pour comprendre. La première est une consommation : le texte défile, l'esprit se détend, rien n'est exigé. La seconde est un travail : le texte résiste, l'esprit s'engage, quelque chose se construit. Les deux sont légitimes, mais elles ne doivent pas être confondues. Une soirée de lecture de détente ne remplace pas une session de lecture active, pas plus qu'une promenade ne remplace une séance d'entraînement.",
 "La reconstruction est le test qui sépare les deux. Si tu ne peux rien dire du texte après l'avoir fermé, tu t'es reposé — et c'est bien. Si tu veux comprendre, il faut reprendre, plus lentement, avec une intention. Le protocole organise cette reprise : les textes sont fermés, les questions posées, et la reconstruction devient la preuve tangible que la lecture a eu lieu."],
7: [
 "L'ennui a une vertu supplémentaire : il est un signal de saturation. Quand tout est nouveau, rien n'est traité ; l'esprit passe sans s'arrêter. L'ennui apparaît quand le flux ralentit et que l'esprit doit s'occuper de ce qui est déjà là. Dans ce sens, s'ennuyer est une preuve que le système fonctionne : il revient à la maison. La culture qui fuit l'ennui fuit ce retour.",
 "La pratique du vide prépare aussi à une autre compétence : la capacité de choisir ce que l'on fait de son temps libre. Une personne qui sait rester sans stimulus est une personne qui peut choisir ses activités par désir, et non par peur du vide. Le vide n'est pas le but ; il est le terrain où le choix redevient possible. Ceux qui ne supportent jamais le vide ne choisissent jamais vraiment : ils remplissent, par réflexe."],
8: [
 "Observer développe aussi la mémoire du regard. Quand tu observes sans photographier, tu es obligé de retenir par toi-même : l'image doit être construite dans l'esprit, pas récupérée sur un écran. Cette contrainte change la qualité de la rétention. Les scènes réellement observées restent ; les scènes photographiées passent. L'appareil n'est pas un ennemi ; il est un délégataire — et la délégation a un prix.",
 "La question de la photographie révèle le principe général de l'observation : plus l'outil fait le travail, moins le regard travaille. Le protocole choisit volontairement de laisser l'outil de côté pendant les missions. Ce n'est pas une nostalgie ; c'est un réglage : pour que l'attention fasse son travail, il faut parfois lui rendre la responsabilité entière."],
9: [
 "Le passage de l'effort à l'habitude ne se fait pas en ligne droite. Il y a des semaines où la session est facile, d'autres où elle résiste. Cette variation est normale : les conditions changent, la fatigue varie, les tentations fluctuent. Ce qui maintient la pratique, ce n'est pas la constance des sensations, c'est la constance du rendez-vous. La session a lieu, qu'elle soit facile ou difficile.",
 "Il faut aussi prévoir les jours de rupture, non comme des échecs, mais comme des événements du calendrier. La vie a des urgences, des voyages, des moments où la session n'aura pas lieu. La compétence n'est pas d'éviter ces ruptures ; elle est de savoir reprendre après. Une pratique qui reprend après une pause est une pratique vivante ; une pratique qui s'arrête au premier manquement était une pratique fragile. Le retour est la vraie mesure."],
10: [
 "L'honnêteté sur la science a une conséquence sur le langage du protocole. On ne parle pas de réinitialiser le cerveau, parce que ce serait une promesse fausse ; on parle de ré-entraîner des habitudes, parce que c'est ce qui se passe réellement. Ce choix de langage n'est pas une précaution de communication ; c'est une décision de méthode. Un entraînement honnête dit ce qu'il fait, et ne promet que ce qu'il peut tenir.",
 "Cette honnêteté protège aussi la motivation. Les promesses magiques produisent des espoirs immenses, puis des déceptions profondes. Un protocole modeste produit des progrès réels, qui suffisent à nourrir la pratique. La régularité n'a pas besoin de miracles ; elle a besoin de vérité sur le mécanisme, et de patience sur le calendrier."],
11: [
 "La fermeture a une dimension émotionnelle qu'il faut reconnaître : fermer, c'est renoncer. Renoncer à ce que l'onglet promettait, renoncer à la possibilité de le lire plus tard, renoncer à l'idée d'être quelqu'un qui garde tout. Ce renoncement est inconfortable, mais il est la condition de la présence. Une chose fermée est une chose que l'on a vraiment choisie de ne pas faire — et ce choix libère.",
 "L'entraînement à la fermeture peut commencer par des gestes minuscules : fermer un onglet avant d'en ouvrir un autre, fermer une application en sortant, fermer une liste avant de dormir. Chaque fermeture est une répétition de la décision. À force, la capacité de fermer devient un réflexe, et l'environnement s'allège. La fermeture n'est pas une perte ; c'est une prise de décision qui rend l'attention possible."],
12: [
 "La durée seule ne suffit pas : il faut aussi que la durée soit orientée. Rester vingt minutes sur un écran n'est pas de la profondeur ; rester vingt minutes avec une question, en revenant sans cesse à elle, en la laissant travailler, c'est autre chose. La profondeur est une durée avec une intention. L'intention donne au temps sa qualité : elle transforme l'attente en recherche, la répétition en exploration.",
 "Cette distinction éclaire le rôle des sessions. Une session n'est pas un minuteur qui tourne ; c'est une intention soutenue. Le minuteur protège l'intention des interruptions ; il ne la remplace pas. C'est pour cela que le protocole demande de choisir la tâche avant de verrouiller la durée : la durée sans tâche est vide, la tâche sans durée est fragile. Les deux ensemble forment l'unité d'entraînement."],
13: [
 "Le tri entre signal et bruit s'apprend aussi par la pratique de la lecture. Un texte long est un signal organisé : il a été écrit, révisé, structuré. Le flux est un bruit organisé : il a été sélectionné pour attirer, pas pour informer. Choisir le texte long, c'est choisir une source dont la structure travaille pour la compréhension, au lieu d'une source dont la structure travaille contre elle.",
 "La reconstruction est un instrument de tri : elle force à distinguer ce qui a traversé le bruit et ce qui a été retenu. Après une session de lecture, ce qui reste est le signal ; ce qui s'est évaporé était le bruit, même s'il semblait important sur le moment. L'entraînement rend ce tri de plus en plus fin, et la journée de plus en plus légère."],
14: [
 "L'effort de comprendre a un prix immédiat : il est moins agréable que la réception. Suivre une explication est facile et plaisant ; reconstruire est lent et exigeant. Ce contraste explique pourquoi tant d'apprentissages s'arrêtent à la réception : le plaisir du flux y est plus fort que le travail de la construction. L'entraînement sérieux accepte ce contraste et organise le travail malgré lui.",
 "La compensation vient de la fierté de la construction : une idée que l'on peut enseigner est une idée qui nous appartient. Elle ne dépend plus de la source ; elle est devenue la nôtre. Cette transformation est la récompense réelle de l'effort, et elle se reconnaît à un signe : on peut répondre aux questions, pas seulement répéter. C'est ce passage que le mode EXPLAIN rend visible, session après session."],
15: [
 "Le vide a aussi un rapport à la durée qui mérite d'être précisé : la première minute est presque toujours la plus difficile. L'esprit, habitué au flux, proteste dès que l'entrée s'arrête. Si l'on cède à la protestation, on n'apprend rien ; si l'on reste, la protestation s'épuise d'elle-même. La tolérance au vide se construit donc par des durées qui dépassent la protestation, pas par des durées qui s'arrêtent avant.",
 "La question finale — qu'est-ce qui occupait ton esprit ? — transforme la session en observation de soi. Le contenu de l'agitation est une information : les préoccupations réelles, les projets reportés, les tensions non traitées. Le vide ne crée pas ces contenus ; il les rend visibles. Et ce qui est visible peut être traité, au lieu de rester dans l'arrière-plan de la journée."],
16: [
 "La reconstruction a une vertu qui dépasse la lecture : elle entraîne la pensée en général. Reformuler une idée, c'est pratiquer l'opération qui se cache derrière toutes les compréhensions : transformer du matériau brut en structure personnelle. Cette opération sert dans les conversations, les réunions, les décisions. Chaque restitution est une répétition de la pensée elle-même.",
 "Il y a une dernière remarque : la reconstruction ne doit pas être confondue avec le résumé. Le résumé cherche l'exhaustivité et la fidélité ; la reconstruction cherche ce qui a survécu. Un résumé peut être fait sans comprendre ; une reconstruction ne le peut pas. C'est pour cela que le protocole n'impose pas de longueur : la question n'est pas de couvrir le texte, mais de montrer ce que le texte a fait en toi."],
17: [
 "Le geste de vérification se distingue des autres distractions par sa fréquence et sa banalité. On ne le remarque presque plus, tellement il est intégré. Cette invisibilité est sa force : un geste invisible ne peut pas être interrogé. La première étape de l'entraînement est donc de rendre le geste visible — par une marque, un compteur, une question. Ce qui est visible peut devenir un choix.",
 "Le retard volontaire a une propriété remarquable : il transforme la relation à la tension. Au lieu de subir la tension comme une urgence, on l'observe comme un phénomène qui monte et qui redescend. La plupart des tensions de vérification retombent en quelques minutes. Celui qui le sait cesse de croire que la tension est un ordre ; il sait que c'est une vague, et qu'elle passera."],
18: [
 "Le muscle de direction a besoin de conditions pour s'exercer : une direction claire, des concurrents absents, un retour possible. Sans direction, il vagabonde ; avec des concurrents, il se fatigue ; sans retour, il s'égare. Les sessions du protocole réunissent les trois conditions : une tâche choisie, un environnement réduit, et la règle du retour. C'est pour cela qu'elles sont efficaces : elles ne demandent pas plus de force, elles organisent mieux la direction.",
 "La direction s'entraîne aussi dans la vie courante, hors des sessions. Choisir une chose à regarder dans une file d'attente, une chose à écouter dans une conversation, une chose à terminer avant d'en commencer une autre : ce sont des répétitions discrètes du même muscle. L'entraînement réussi est celui qui ne reste pas dans la salle de session ; il se répand dans les gestes ordinaires, et la journée entière devient un terrain d'exercice."],
19: [
 "Il y a une objection à cette analyse : tout le monde n'est pas également exposé, et certains usages du numérique sont profondément personnels et précieux. C'est vrai, et cette objection ne contredit pas le modèle ; elle le précise. L'économie de l'attention ne dit pas que toute attention passée en ligne est volée ; elle dit que l'attention est une ressource qui peut être captée ou donnée. La différence tient à la conscience de la transaction. Regarder volontairement un contenu choisi n'est pas la même chose que défiler sans décision : dans un cas, on donne ; dans l'autre, on est pris.",
 "La stratégie qui découle de cette distinction n'est pas la privation ; c'est l'étiquetage. Avant d'ouvrir une application, se demander : cette heure est-elle un don choisi ou une prise automatique ? L'étiquetage ne change pas la mécanique, mais il change le rapport : on entre dans la transaction les yeux ouverts, et l'on peut en sortir quand on veut. Les sessions du protocole sont des moments où la transaction est entièrement choisie : le temps y est donné à soi, pas pris par un système."],
20: [
 "Une nuance importante : la comparaison entre l'écriture et le numérique a ses limites. L'écriture a demandé des siècles pour produire ses institutions ; le numérique a changé d'échelle en une génération. Les institutions d'usage — écoles du numérique, éducation à l'information, codes de pratique — en sont à leurs débuts, et elles sont inégalement réparties. Cette différence d'échelle n'invalide pas la leçon ; elle la rend plus urgente.",
 "Il y a une seconde nuance : les technologies ne sont pas équivalentes dans leurs effets. L'écriture a remplacé une mémoire individuelle par une mémoire externe ; le flux remplace une attention dirigée par une attention sollicitée. La différence est qualitative : l'écriture a déplacé la fonction, le flux a capté la ressource. Comprendre cette différence évite deux erreurs symétriques : croire que tout est pareil qu'avant, ou croire que tout est radicalement nouveau. C'est un mélange, et c'est le mélange qu'il faut apprendre à naviguer."],
21: [
 "La mémoire de travail a une propriété supplémentaire qui explique sa fragilité : elle est sensible aux interférences de nature similaire. Deux informations verbales se gênent plus que deux informations de types différents. C'est pour cela qu'écouter en lisant est si difficile : les deux utilisent le même canal. Cette sensibilité au type de contenu est une information pratique : quand la tâche est verbale, l'environnement doit être silencieux ; quand elle est visuelle, les distractions verbales sont moins coûteuses.",
 "Il y a une stratégie connue pour soutenir la scène : la notation externe. Écrire ce que l'on doit retenir libère la mémoire de travail : on n'a plus à tenir l'élément en tête, il est posé sur le papier. Cette stratégie est largement utilisée, mais elle a une limite : la note ne remplace pas la compréhension. Elle protège l'information, pas le raisonnement. Le raisonnement, lui, a toujours besoin de la scène — et la scène a toujours besoin d'être libre."],
22: [
 "Le paradoxe de la contrainte a une limite qu'il faut examiner : toute contrainte n'est pas libératrice. Une contrainte subie, arbitraire, sans sens, produit de la révolte et de l'épuisement. La contrainte libératrice a trois propriétés : elle est choisie, elle est proportionnée, et elle sert une valeur. Choisie : c'est moi qui l'ai posée. Proportionnée : elle ne demande pas l'impossible. Servante : elle protège ce qui compte pour moi. Ces trois propriétés transforment le mur en structure.",
 "Cette analyse explique pourquoi les cadres du protocole sont négociables et progressifs. Les durées commencent courtes, les modes sont choisis, les jours sont flexibles. Le cadre n'est pas une prison ; c'est un accord que l'on passe avec soi-même, et que l'on peut réviser. La liberté n'est pas dans l'absence d'accord ; elle est dans la capacité de le passer, de le tenir, et de le réviser en connaissance de cause."],
23: [
 "La vitesse a aussi une dimension collective qu'il ne faut pas ignorer. Quand une société entière accélère, la lenteur individuelle devient difficile : les autres attendent, les systèmes sont réglés sur le rapide, la lenteur est pénalisée. Cette pression est réelle, mais elle n'est pas totale. Il existe des îlots de lenteur choisis — la lecture, la conversation longue, la promenade, la session — et ces îlots sont plus accessibles qu'on ne le croit. La question n'est pas de ralentir toute la société ; c'est de se donner des îlots où le tempo nous appartient.",
 "L'entraînement a un effet secondaire précieux : il change la perception de la lenteur chez les autres. Une personne qui pratique la lenteur devient plus tolérante à celle des autres : elle cesse d'attendre que l'on réponde vite, elle laisse les phrases finir, elle accepte les silences. La lenteur n'est pas seulement une protection personnelle ; c'est une politesse nouvelle, offerte à ceux qui nous entourent."],
24: [
 "Il y a une question pratique : comment distinguer le besoin réel de vérification de la pulsion conditionnée ? Un test simple existe : la différence entre vérifier quelque chose de précis et vérifier pour vérifier. Si tu peux dire ce que tu cherches — un horaire, une réponse, un message attendu — le besoin est réel. Si tu ne peux pas le dire, c'est une pulsion. Ce test prend une seconde, et il suffit souvent à éclairer le geste.",
 "Une autre observation concerne le moment du geste. Les vérifications automatiques ne sont pas réparties au hasard : elles se concentrent dans les moments de transition, d'ennui ou de difficulté. Le téléphone est la porte de sortie habituelle dès que la tâche résiste. Reconnaître ces moments — transition, ennui, blocage — permet de prévoir le réflexe et de préparer une autre réponse : se lever, respirer, reformuler la difficulté. Le réflexe n'est pas supprimé ; il est précédé."],
25: [
 "Le temps long a une structure que l'entraînement rend visible : il est fait de segments, et chaque segment a son propre type de difficulté. Le début est porté par la nouveauté ; le milieu est le plus fragile, quand la nouveauté s'use ; la fin est portée par la perspective de l'achèvement. Les abandons se concentrent au milieu. L'entraînement à la session apprend précisément à traverser ce milieu : quand la tâche n'est plus nouvelle et pas encore finie, rester.",
 "Cette compétence se transfère à des échelles différentes. Le milieu d'une session et le milieu d'un projet obéissent à la même loi : la motivation initiale est consommée, la fin n'est pas encore visible, et c'est là que la discipline prend le relais. Les sessions du protocole sont de petites traversées de ce milieu. Chacune enseigne que le milieu passe, que la fin arrive, et que la traversée n'exige pas de force particulière — seulement la décision de ne pas changer de cap."],
26: [
 "La présence a une composante que l'on oublie souvent : la qualité de l'attention dépend de ce qui précède. Une journée commencée dans le flux prépare une présence dispersée ; une journée commencée par un moment calme prépare une présence disponible. L'attention n'est pas un état qui se décide à l'instant ; c'est un régime qui se prépare. Les premières minutes de la journée, les premières minutes après le réveil, sont un réglage : ce qu'on y fait oriente le reste.",
 "C'est pour cela que les routines du matin ne sont pas des rituels décoratifs ; ce sont des réglages d'attention. Un moment sans écran, une lecture courte, une marche, une session : autant de façons de régler le régime sur la présence avant que le flux ne le règle sur la dispersion. L'entraînement à la présence commence donc avant les sessions : il commence par la décision de ne pas commencer la journée ailleurs."],
27: [
 "L'attention conjointe pose une question d'économie : elle est une ressource partagée, et son partage a des règles. Une attention donnée entièrement à quelqu'un est un don rare ; une attention partagée avec un écran est un don divisé. Les personnes autour de nous perçoivent la division, même sans la nommer : elles sentent quand elles n'ont qu'une moitié de présence. Cette perception explique une partie des frustrations relationnelles contemporaines, que l'on attribue souvent à tort à d'autres causes.",
 "La pratique de la présence conjointe peut commencer par des gestes minuscules : poser le téléphone face cachée pendant un repas, finir une phrase avant de regarder, ne pas consulter pendant qu'on écoute. Ces gestes ne résolvent pas tous les problèmes de relation, mais ils restaurent le signal de base : tu es là, et ton attention est entière. Ce signal est la fondation de tout le reste ; sans lui, les mots eux-mêmes perdent une partie de leur poids."],
28: [
 "La logique de finir a un coût que l'on découvre à la fin de l'année : on a parcouru beaucoup de textes et construit peu. Le bilan ne se compte pas en titres lus ; il se compte en idées qui restent. Une seule lecture profonde par semaine produit en un an une cinquantaine d'idées réellement possédées. Une lecture de survol quotidienne produit un sentiment d'avancement et presque aucune possession. Le choix n'est pas entre lire et ne pas lire ; il est entre posséder et parcourir.",
 "La reconstruction change aussi la vitesse de lecture, et cette lenteur a un effet paradoxal : elle rend la lecture plus satisfaisante. Un texte que l'on comprend laisse une trace, et la trace produit un plaisir durable — celui de la possession. Le plaisir du défilement est immédiat et s'évapore ; le plaisir de la compréhension est différé et persiste. L'entraînement à la lecture active n'est donc pas une punition de la vitesse ; c'est un échange : la vitesse contre la possession."],
29: [
 "Il faut distinguer deux familles d'interruptions, car elles ne se traitent pas de la même façon : celles qui viennent des autres et celles qui viennent de soi. Les premières peuvent être aménagées : des moments de disponibilité déclarés, des outils en mode silencieux, des réponses différées. Les secondes sont plus difficiles, parce qu'elles viennent de l'intérieur : la pulsion de vérifier, le réflexe de changer, l'envie de passer. Aménager l'environnement aide pour les deux, mais les secondes demandent en plus un travail de reconnaissance.",
 "Un outil utile est le journal des interruptions : noter, pendant une journée, chaque interruption reçue et chaque interruption auto-infligée, avec l'heure et le contexte. Le journal révèle des motifs que l'on ne voit pas : les interruptions se regroupent à certains moments, autour de certains types de tâches, après certaines émotions. Une fois le motif vu, l'aménagement devient précis : on protège le moment fragile, on change le type de tâche, on prépare la réponse. L'entraînement commence par la mesure, pas par la volonté."],
30: [
 "L'observation prolongée a une limite qu'il faut reconnaître : elle ne produit pas toujours des découvertes spectaculaires. Parfois, on regarde une chose trois minutes et l'on ne trouve rien de neuf. Ce résultat est une donnée, pas un échec : il dit que la chose est connue de notre regard, ou que nos questions n'étaient pas les bonnes. La pratique de l'observation n'est pas une machine à surprises ; c'est une école du regard, et ses résultats s'accumulent sur des semaines, pas sur une session.",
 "Il y a aussi une vertu de l'observation qui ne se mesure pas en découvertes : la décompression du regard. Observer une chose du réel, lentement, sans objectif de production, c'est sortir du régime où tout doit être consommé. La durée de l'observation est un repos pour l'attention — non pas un repos du vide, mais un repos de la demande. On ne demande plus au réel de divertir ; on lui demande simplement d'être là, et l'on s'accorde à son rythme."],
31: [
 "Cette distinction a une conséquence sur la façon de parler de soi. Les personnes qui se décrivent comme « distraites » ou « incapables de se concentrer » s'enferment dans une identité : la description devient une prophétie, et chaque difficulté confirme l'identité. Les personnes qui parlent en termes de compétences disent : « aujourd'hui, j'ai eu du mal à rester ». La différence semble mince, mais elle est décisive : la première phrase ferme la porte, la seconde l'ouvre.",
 "L'entraînement est aussi un apprentissage du langage : apprendre à décrire ce qui se passe au lieu de se juger. La trace aide : elle fournit le vocabulaire de la description — durée, retours, conditions, tendance. Quand le langage devient descriptif, la pratique devient possible : on peut ajuster ce qui est décrit. C'est le passage de l'identité à la pratique, et c'est le passage que le protocole organise jour après jour."],
32: [
 "La qualité a un ennemi particulier : la comparaison. On juge sa session par rapport à une session idéale, ou par rapport à ce que l'on imagine des autres. Cette comparaison est toujours injuste : elle compare des conditions différentes, des histoires différentes, des objectifs différents. La seule comparaison qui a un sens est celle que l'on fait avec soi-même, à conditions comparables : ma session d'aujourd'hui par rapport à ma session de la semaine dernière, dans des conditions semblables. Toute autre comparaison est du bruit.",
 "Le protocole organise cette comparaison honnête par la trace : les données sont datées, avec leurs conditions, et la tendance se lit sur la série. La question n'est pas « suis-je meilleur que quelqu'un ? » ; elle est « est-ce que ma pente va dans le bon sens ? ». La pente est la seule mesure de la qualité qui respecte les conditions réelles. Et la pente se construit par des sessions régulières, pas par des sommets."],
33: [
 "Le lien corps-esprit a une application directe dans les sessions : la posture est un réglage d'entrée. Avant de commencer une session de concentration, s'asseoir, poser les pieds, stabiliser les mains : ces gestes prennent dix secondes et changent la qualité du maintien. Le corps est aussi un indicateur pendant la session : quand l'agitation monte, la posture se dégrade, et la reprise peut commencer par le corps — se redresser, respirer, relâcher les épaules — avant de revenir à la tâche.",
 "Cette boucle fonctionne aussi dans l'autre sens : l'attention influence le corps. Une attention tendue crispe ; une attention fluide détend. Observer cette influence, c'est apprendre à lire l'état réel au lieu de s'en tenir aux pensées. Les questions subjectives du protocole — calme, énergie — captent une partie de cette information corporelle. L'entraînement sérieux écoute le corps comme un instrument de mesure, pas comme un accessoire."],
34: [
 "L'économie du temps réel a une conséquence que l'on découvre tard : elle érode la confiance. Quand tout le monde répond immédiatement, l'absence de réponse devient inquiétante ; quand tout le monde est disponible, la disponibilité cesse d'être un don. Le temps réel transforme les relations en attentes, et les attentes en tensions. Le délai volontaire restaure un signal précieux : je réponds quand c'est le moment pour moi, et mon absence n'est pas une alerte. Ce signal est une forme de liberté partagée.",
 "Il y a une règle pratique simple pour commencer : définir des fenêtres de consultation au lieu de rester connecté en permanence. Deux ou trois moments par jour suffisent pour la plupart des besoins réels. À l'intérieur de ces fenêtres, on répond vite ; en dehors, on est absent sans culpabilité. Cette architecture transforme le temps réel en temps choisi : l'immédiateté n'est plus un état permanent, c'est un outil que l'on ouvre et que l'on ferme."],
35: [
 "La peur de rester se manifeste souvent par des signes que l'on ne reconnaît pas : un inconfort vague, une envie de bouger, une pensée qui cherche une sortie. Ces signes ne sont pas des jugements sur la tâche ; ce sont des réactions à la durée. L'entraînement consiste à les reconnaître pour ce qu'ils sont — des réactions, pas des informations — et à ne pas leur obéir automatiquement. On ne nie pas l'inconfort ; on le laisse être là, sans le suivre.",
 "Il y a une découverte surprenante dans cette pratique : ce que l'on fuyait est souvent plus petit que la peur. La tâche redoutée s'avère faisable ; la pensée inconfortable s'avère gérable ; la conversation exigeante s'avère possible. La fuite n'était pas proportionnée à l'objet ; elle était proportionnée à la peur. Et la peur diminue avec la pratique : chaque fois que l'on reste, on apprend que rester est possible. C'est ainsi que la capacité de rencontre se construit, sans héroïsme, par de petites traversées."],
36: [
 "Il y a une distinction utile entre les architectures de captation et les architectures de protection : les premières sont conçues pour être ouvertes, fluides, sans fin ; les secondes sont conçues pour être closes, bornées, finies. Un défilement infini est une architecture ouverte ; un texte paginé est une architecture close. Le protocole est une architecture close : des sessions bornées, des durées définies, des fins claires. Cette clôture n'est pas une limitation ; c'est une protection de l'attention.",
 "Choisir ses architectures est un acte d'ingénierie personnelle que l'on peut pratiquer dès aujourd'hui : désactiver les notifications non essentielles, fixer des limites de temps, utiliser des modes de concentration, fermer les onglets. Chaque choix est petit, mais l'ensemble construit un environnement. Et l'environnement agit en continu, pour ou contre. La question n'est pas de savoir si l'on est fort ; elle est de savoir quel environnement on a construit, et s'il travaille pour nous."],
37: [
 "L'histoire de l'attention enseigne aussi une chose sur la nouveauté : chaque époque a cru que sa crise de l'attention était la première. Les romains se plaignaient des distractions de la ville, les moines des bruits du monde, les modernes du télégraphe, puis du cinéma, puis de la télévision. Cette répétition a deux leçons. La première : la crainte est ancienne, et elle n'a pas toujours raison. La seconde : elle signale pourtant un vrai travail, celui d'organiser l'usage des nouveaux outils.",
 "Cette double leçon protège de deux erreurs : la panique et la négligence. La panique croit que tout est perdu ; la négligence croit que rien n'a changé. La pratique sérieuse se tient entre les deux : elle reconnaît la nouveauté réelle — l'échelle, la puissance, la pervasivité — et elle répond par l'ancienne méthode : des institutions, des pratiques, des cadres. Le protocole est une réponse modeste à cette échelle : un cadre individuel, dans une époque qui n'a pas encore construit les cadres collectifs."],
38: [
 "Le jugement a une source profonde qu'il faut nommer : l'éducation à la performance. On a appris tôt que les résultats se notent, que les erreurs se pénalisent, que l'effort se mesure. Cette grille est utile à l'école ; elle est toxique dans la pratique personnelle, parce qu'elle transforme chaque session en examen. Le protocole propose une grille inverse : la session n'est pas notée, elle est complétée. La complétion est une donnée binaire — elle a eu lieu, ou non — et cette simplicité protège du jugement.",
 "Il y a une dernière pratique pour domestiquer le jugement : le rituel de clôture. À la fin de chaque session, une phrase de description au lieu d'une phrase d'évaluation : « j'ai tenu vingt minutes, je suis revenu trois fois, le bruit de la rue m'a dérangé au début ». Cette phrase est neutre, datée, utilisable. Elle prépare la session suivante sans la charger. Le rituel de clôture transforme la fin de session en point de départ, et c'est exactement la fonction d'un bon entraînement : tourner la page sans se juger."],
39: [
 "Il faut examiner une objection : la surface n'est-elle pas le mode naturel de l'attention dans un monde riche ? L'attention est effectivement attirée par la variété, et la variété est une ressource du monde. Mais il y a une différence entre être attiré et être gouverné. L'attention naturelle s'oriente, s'arrête, s'engage ; l'attention gouvernée par le flux ne s'arrête plus, elle passe. La surface n'est pas le problème ; la surface sans fin l'est. Le problème n'est donc pas la variété, c'est l'absence de point d'arrêt.",
 "Une seconde objection concerne la valeur : ne faut-il pas être superficiel pour survivre dans un monde qui change vite ? Cette crainte confond la vitesse d'information et la profondeur de compréhension. S'orienter vite ne demande pas de tout comprendre ; cela demande de savoir trier, et le tri repose justement sur une compréhension profonde de ses propres critères. La surface mal servie est celle qui n'a jamais été contrebalancée : on passe sans savoir pourquoi on passe. La profondeur, elle, donne au passage son sens : on sait ce que l'on survole, pourquoi on le survole, et quand il faut descendre. Loin d'être incompatible avec la vitesse, la profondeur est ce qui rend la vitesse intelligente.",
 "Il y a enfin une question de temps : comment organiser la profondeur dans des journées déjà pleines ? La réponse n'est pas de tout ralentir ; c'est de réserver des enclaves. Une enclave de profondeur par jour — une lecture, une session, une conversation — suffit à maintenir la capacité. L'enclave n'a pas besoin d'être longue ; elle a besoin d'être entière. Une heure de présence complète vaut mieux que huit heures de présence partielle. Cette proportion est difficile à accepter, parce qu'elle contredit la logique du volume ; mais c'est elle que l'expérience vérifie : c'est la qualité de l'engagement, pas la quantité de temps, qui produit la compréhension."],
40: [
 "Un point de méthode : la relation entre attention et mémoire est souvent mal comprise parce que l'on confond deux processus — la trace et la récupération. La trace est ce qui se grave pendant l'encodage ; la récupération est ce qui la rend accessible. L'entraînement à l'attention travaille les deux : les sessions profondes créent des traces riches, et les restitutions espacées entraînent la récupération. Un contenu dont la trace est riche mais qui n'est jamais récupéré finit par s'effacer ; un contenu récupéré souvent, même avec une trace moyenne, se maintient. La pratique complète associe les deux : traiter profondément, puis revenir.",
 "Il faut aussi examiner la croyance selon laquelle plus d'information égale plus de mémoire. Cette croyance est fausse pour une raison simple : l'information excédentaire est un bruit qui encombre la récupération. Un étudiant qui surligne tout ne se souvient de rien de précis ; un lecteur qui choisit l'essentiel et le reformule se souvient de l'essentiel. La sélection est une opération de mémoire autant qu'une opération d'attention. Elle demande de savoir ce que l'on va laisser tomber — et laisser tomber, c'est déjà décider.",
 "La dernière remarque concerne l'oubli lui-même. Le protocole ne promet pas de tout retenir ; il promet de mieux retenir ce qui compte. Cette promesse modeste est la seule tenable, et elle est la plus utile : une mémoire qui garde l'essentiel des journées est une mémoire qui donne une vie avec épaisseur. L'oubli du détail n'est pas une perte ; c'est la condition de la hiérarchie. L'entraînement n'est pas une lutte contre l'oubli ; c'est une collaboration avec lui — pour que ce qui reste soit ce qui compte."],
41: [
 "Il y a une nuance importante sur l'installation des habitudes : la répétition ne suffit pas, il faut la répétition avec conséquence. Une action répétée sans résultat ne s'installe pas ; une action répétée qui produit un effet — une session complétée, une trace, une sensation — s'installe. C'est pour cela que les sessions comptent même quand elles sont moyennes : elles produisent la conséquence de base, la complétion. La complétion est le carburant de l'habitude ; sans elle, la répétition s'essouffle.",
 "Une seconde nuance concerne les signaux d'arrêt. Les habitudes ont besoin d'une fin claire pour ne pas déborder : la session finit, le livre se ferme, la promenade s'achève. Les interfaces modernes suppriment souvent ces signaux — le défilement n'a pas de fin — et les habitudes deviennent des états sans issue. Le protocole restaure les signaux : une durée affichée, une fin définie, une complétion enregistrée. Le signal de fin est aussi important que le signal de départ : c'est lui qui permet de fermer la séquence et de passer à autre chose sans résidu.",
 "Il y a enfin une question d'équilibre entre habitude et décision. Une pratique trop automatisée devient une routine vide ; une pratique trop décidée devient épuisante. La solution n'est pas de choisir ; c'est d'alterner : l'habitude exécute le cadre, et la décision garde le cap. Une fois par semaine, on peut s'arrêter et demander : ce cadre me sert-il encore ? Cette question périodique est une décision qui réoriente ; les autres jours, l'habitude travaille. C'est ainsi que l'entraînement reste vivant : suffisamment automatisé pour tenir, suffisamment questionné pour progresser."],
42: [
 "Il faut éviter une erreur de diagnostic : attribuer à l'écran ce qui appartient à l'organisation du temps. L'écran peut être un outil de profondeur — on y écrit, on y lit, on y apprend — et le papier peut être un outil de dispersion. La différence n'est pas matérielle ; elle est structurelle. Ce qui fragmente, ce sont les dispositifs qui suppriment les fins, multiplient les saillances et récompensent le passage : les flux, les notifications, les recommandations. La critique ne vise pas un objet, mais une architecture. Cette précision évite les fausses solutions — jeter l'écran — et oriente vers les vraies : aménager l'architecture.",
 "Une seconde erreur serait de croire que la profondeur est un privilège de classe ou de temps libre. La profondeur demande une heure, parfois moins ; elle demande surtout une intention et une protection. Elle est accessible dans une journée chargée, à condition d'être traitée comme un rendez-vous non négociable. Les obstacles ne sont pas seulement matériels ; ils sont culturels : la profondeur est perçue comme improductive, la lenteur comme un échec. Changer cette perception est un travail individuel et collectif : chaque personne qui revendique sa session, sa lecture, sa conversation longue, contribue à rendre la profondeur légitime.",
 "Enfin, il faut regarder la génération montante avec nuance. Elle n'est pas « perdue » ; elle est entraînée par un environnement que personne n'a choisi. Les jeunes qui grandissent avec le flux développent des compétences réelles — vitesse, parallélisme, adaptation — et des fragilités réelles — maintien, patience, profondeur. Leur situation n'est pas un verdict ; c'est un défi d'éducation. Le protocole, à son échelle, est une réponse à ce défi : une pratique qui rééquilibre ce que l'environnement déséquilibre. La profondeur n'est pas une nostalgie de vieux ; c'est une infrastructure à reconstruire, pour tous."],
43: [
 "Une objection sérieuse mérite examen : si l'usage dépend de la pédagogie, pourquoi les concepteurs ne fournissent-ils pas cette pédagogie ? La réponse est structurelle : leur objectif n'est pas l'usage maîtrisé, c'est la durée de présence. Une pédagogie de l'usage maîtrisé travaillerait contre leur modèle. Il ne faut donc pas attendre des outils qu'ils enseignent leur propre critique ; c'est une tâche qui revient à d'autres institutions — l'école, les médias, les communautés, et finalement l'individu. Cette répartition n'est pas satisfaisante, mais elle est la réalité : la critique des outils viendra de l'extérieur, ou ne viendra pas.",
 "Il y a une seconde nuance : la maîtrise de l'usage n'est jamais définitive. Les outils changent, les interfaces évoluent, les mécanismes se raffinent. La compétence n'est pas de connaître un outil ; c'est de savoir en lire un nouveau : repérer les saillances, les fins supprimées, les invitations. Cette lecture est un réflexe qui s'entretient. Chaque nouvelle application est un exercice : qu'est-ce que cette interface veut que je fasse, et est-ce que je le veux ? Cette question, posée systématiquement, transforme l'utilisateur en lecteur d'interfaces.",
 "La dernière remarque concerne l'idée de protocole elle-même. Un protocole n'est pas une technique ; c'est une intention organisée. Il choisit des outils, fixe des règles, aménage un temps. Le protocole REBOOT n'est pas contre la technique ; il est une technique d'usage de la technique. Il utilise des minuteurs, des textes, des interfaces réduites, et il organise leur usage au service de l'attention. Cette position — ni rejet, ni soumission — est peut-être la plus difficile et la plus nécessaire : habiter la technique avec des règles choisies, au lieu de la subir ou de la fuir."],
44: [
 "Il faut examiner une objection à l'analogie économique : l'attention n'est-elle pas aussi une source de plaisir, pas seulement une ressource ? Si, et l'analogie ne le nie pas ; elle précise seulement le coût. Le plaisir est un signal de valeur, mais il n'est pas la valeur elle-même. Une dépense agréable peut être une bonne dépense si elle est choisie et proportionnée ; elle devient un problème quand elle est automatique et qu'elle dépasse ce que l'on voulait. La question n'est donc pas de supprimer le plaisir ; c'est de le placer dans le budget, au lieu de le laisser vider le compte.",
 "Une seconde précision concerne la notion de dette. L'attention dépensée dans le flux produit une dette particulière : la fatigue de la fragmentation. Cette fatigue n'est pas une simple baisse d'énergie ; c'est un coût composé, qui s'accumule et qui se paie en qualité de pensée, en humeur, en patience. La dette se reconnaît à ses symptômes : la difficulté à commencer, l'intolérance à la lenteur, l'irritabilité. Le repos ne rembourse pas cette dette si l'on reprend le flux dès le réveil ; le remboursement suppose des moments de présence sans stimulation.",
 "Enfin, la métaphore du budget a une limite qu'il faut reconnaître : l'attention n'est pas seulement un stock à gérer, c'est aussi une compétence à développer. Gérer un stock, c'est répartir ; développer une compétence, c'est investir. Les sessions sont des investissements : elles consomment de l'attention aujourd'hui pour produire plus d'attention demain. Cette double nature — ressource et compétence — explique pourquoi l'entraînement est à la fois une économie et une éducation. On ne peut pas seulement économiser l'attention ; il faut aussi l'exercer. Et on ne peut pas seulement l'exercer ; il faut aussi la protéger. Le protocole combine les deux : des sessions qui développent, des cadres qui protègent."],
45: [
 "Une remarque historique précise : le multitâche n'a pas toujours été une valeur. Pendant des siècles, les cultures du travail artisanal valorisaient l'inverse — une tâche, un geste, une fin — parce que la qualité dépendait de l'attention entière. La valorisation du multitâche est moderne, et elle est liée à l'administration : les cadres, les bureaux, les communications croisées. Cette généalogie montre que le multitâche n'est pas une loi naturelle du travail ; c'est un choix culturel, et un choix récent. Ce qui a été choisi peut être révisé.",
 "Il y a une nuance cognitive importante : ce que l'on appelle multitâche est souvent en réalité du changement rapide. L'esprit ne fait pas deux choses à la fois ; il bascule entre deux choses, avec un coût de bascule à chaque passage. La sensation de simultanéité est une illusion de la vitesse : les bascules sont si rapides qu'elles semblent parallèles. Mais chaque bascule paie son coût, et le coût s'additionne. Cette précision change le diagnostic : le problème n'est pas un excès de capacités, c'est un excès de bascules — et les bascules se réduisent par la clôture, pas par l'entraînement à la vitesse.",
 "La dernière remarque concerne la fatigue. Le changement rapide est épuisant non pas parce qu'il demande beaucoup d'effort, mais parce qu'il empêche le repos cognitif. Une tâche tenue longuement entre dans un régime stable, où l'effort diminue ; une tâche changée en permanence reste dans un régime d'alerte, où l'effort ne baisse jamais. C'est pour cela que les journées multitâches épuisent même quand elles ne produisent rien : le régime d'alerte est coûteux en lui-même. Les sessions du protocole sont des fenêtres de régime stable — et cette stabilité est un repos, pas une contrainte."],
46: [
 "Une objection mérite d'être prise au sérieux : la patience ne risque-t-elle pas de devenir une justification de la stagnation ? Oui, si elle est mal comprise. La patience n'est pas une durée subie ; c'est une activité dirigée. Elle se distingue de la stagnation par sa question : qu'est-ce que je fais pendant que j'attends ? Le jardinier travaille pendant la germination ; l'étudiant relit, reformule, cherche pendant la compréhension ; le pratiquant observe, revient, ajuste pendant la session. La patience sans travail est une stagnation déguisée ; le travail sans patience est une agitation stérile. Les deux ne sont pas opposés à la patience ; ils sont ses deux erreurs symétriques.",
 "Une seconde précision concerne la relation entre patience et impatience. L'impatience n'est pas l'ennemie de la patience ; elle en est le carburant. C'est la tension de l'impatience qui signale que le temps de maturation est en cours. Sans impatience, il n'y aurait rien à traverser ; la patience n'aurait pas d'objet. La compétence n'est pas d'éliminer l'impatience, mais de la lire : quand elle monte, c'est le signal d'un travail en cours, pas d'une erreur. Cette lecture transforme l'inconfort en information, et l'information en pratique.",
 "Enfin, la patience a une dimension sociale que l'on oublie : elle est aussi ce que l'on offre aux autres. Attendre que quelqu'un finisse sa phrase, laisser une idée se former, ne pas interrompre le silence : ce sont des actes de patience, et ce sont des dons de présence. Une personne entraînée à la patience intérieure devient capable de cette générosité extérieure. L'entraînement à l'attention n'est donc pas seulement un travail sur soi ; c'est une préparation à la relation. La patience est la politesse profonde de l'attention : elle dit à l'autre que son temps a de la valeur."],
47: [
 "Il faut préciser un mécanisme : la nouveauté et la répétition ne sont pas en conflit au niveau du cerveau ; elles sont en dialogue. La nouveauté attire, et c'est elle qui oriente l'attention vers un objet ; la répétition approfondit, et c'est elle qui transforme l'objet en connaissance. Un apprentissage réussi utilise les deux : la nouveauté pour commencer, la répétition pour continuer. Les erreurs viennent du déséquilibre : trop de nouveauté, et l'on ne commence jamais rien ; trop de répétition, et l'on ne découvre plus rien. L'entraînement cherche l'équilibre, et l'équilibre se règle en observant ses propres réactions.",
 "Une seconde nuance concerne la peur de la répétition : elle est souvent une peur de l'ennui, et l'ennui est mal nommé. L'ennui n'est pas une propriété de l'activité ; c'est une propriété du rapport à l'activité. La même lecture peut ennuyer quelqu'un qui survole et passionner quelqu'un qui cherche. L'ennui est un signal de l'intérieur — il dit que l'attention n'est pas engagée — et ce signal peut être lu de deux façons : comme un ordre de changer, ou comme une invitation à chercher plus profond. La pratique apprend la seconde lecture : au lieu de fuir l'ennui, on le traverse, et l'on découvre souvent que l'objet avait plus de couches que prévu.",
 "Enfin, il faut reconnaître que la répétition a un coût psychologique réel : elle produit des plateaux. Pendant des semaines, rien ne semble changer ; les sessions se ressemblent, la progression semble nulle. Ce plateau n'est pas un échec ; c'est une phase de consolidation, où les acquis se stabilisent avant la prochaine montée. Ceux qui abandonnent au plateau ne découvrent jamais ce qui vient après ; ceux qui tiennent savent que le plateau est le pont. L'entraînement à la répétition est donc aussi un entraînement à la confiance : croire que le travail invisible prépare le visible."],
48: [
 "Il faut détailler le mécanisme de consolidation pour en tirer des règles pratiques. La consolidation n'est pas uniforme : elle traite différemment ce qui a été compris et ce qui a été seulement rencontré. Ce qui a été compris — relié, reformulé, réorganisé — a une chance d'être intégré ; ce qui a été rencontré passivement se dégrade. Cette sélectivité donne un sens nouveau à la reconstruction : elle prépare la matière que le sommeil va consolider. Une journée de lecture active suivie d'une nuit régulière produit plus que la somme de ses parties.",
 "Une seconde règle pratique concerne le moment des sessions. Les sessions du soir suivies d'une nuit de sommeil bénéficient de la consolidation immédiate ; les sessions du matin en bénéficient aussi, mais après une nuit qui a déjà consolidé la veille. Les deux ont leur place, mais la régularité compte plus que le moment. La vraie règle est de ne pas sacrifier le sommeil au rituel : une session tardive qui retarde le coucher coûte plus qu'elle ne rapporte. L'entraînement à l'attention et l'hygiène du sommeil sont deux faces du même travail : la construction des traces.",
 "Enfin, il faut dire ce que le sommeil n'est pas : il n'est pas un temps mort entre deux journées, ni un lieu de performance. Le sommeil est un temps de travail invisible, et le traiter comme une perte est une erreur culturelle profonde. Les sociétés qui valorisent l'éveil au détriment du repos produisent des journées longues et des traces pauvres. Le protocole ne peut pas réparer cette culture, mais il peut y résister : en traitant le sommeil comme un allié, en ne programmant pas les sessions contre lui, et en observant le lien entre une nuit courte et une session difficile. Cette observation simple transforme le sommeil en donnée d'entraînement, et la donnée en pratique."],
49: [
 "Il faut prendre au sérieux une objection : si le monde est reconstruit par l'attention, le monde réel n'existe-t-il plus ? Si, il existe — comme matière première. La reconstruction n'est pas une invention ; c'est une sélection et une organisation du réel. Le monde fournit les fragments ; l'attention choisit, relie, interprète. Cette distinction évite deux erreurs : le réalisme naïf, qui croit que le monde se donne tel quel, et le relativisme paresseux, qui croit que tout est dans la tête. La vérité est entre les deux : le réel est là, et la qualité de notre rencontre dépend de l'attention que nous lui donnons.",
 "Une seconde nuance concerne la responsabilité de la reconstruction. Si l'attention construit le monde vécu, alors la fragmentation n'est pas seulement une gêne personnelle ; c'est une dégradation de la qualité de l'expérience commune. Les récits fragmentés — ceux que le flux assemble — produisent des mondes incohérents, où les événements n'ont ni cause ni suite. L'entraînement à la reconstruction est donc un acte de résistance épistémique : il restaure des récits construits, où les fragments s'organisent. Cette résistance se pratique d'abord sur les textes, puis elle s'étend : reconstruire sa journée, sa semaine, ses relations, c'est reprendre la main sur son propre monde.",
 "Enfin, la reconstruction a une dimension éthique : elle change le rapport aux autres. Quand on reconstruit ce que quelqu'un a dit — au lieu de répéter ses mots ou de les oublier — on lui rend une forme de justice : son propos est devenu compréhensible. L'écoute active est une reconstruction en temps réel. L'entraînement à la reconstruction prépare donc l'écoute : la capacité de reformuler ce que l'on a entendu, de vérifier qu'on l'a compris, de répondre à ce qui a été dit et non à ce qu'on imaginait. L'attention n'est pas seulement un instrument de connaissance ; c'est un instrument de relation, et la reconstruction en est la clé."],
50: [
 "Il faut anticiper une difficulté de la maintenance : la monotonie. Après des mois de pratique, les sessions peuvent sembler répétitives, et la répétition peut sembler vide. Cette sensation est normale, et elle est dangereuse seulement si elle n'est pas comprise. La monotonie de la pratique n'est pas la preuve qu'elle ne sert plus ; c'est la preuve qu'elle est devenue une habitude — et l'habitude est précisément ce que l'on voulait construire. La pratique qui semble monotone travaille en arrière-plan, comme la respiration : on ne la remarque pas, mais sans elle, tout s'arrête.",
 "Une seconde difficulté est le retour de la fragmentation. Après des semaines de pratique, une période chargée arrive, les sessions s'espacent, et le flux reprend sa place. Ce retour n'est pas une trahison ; c'est un test. La vraie compétence n'est pas de ne jamais retomber ; c'est de savoir reconnaître la chute et de revenir sans drame. Le protocole l'a appris pendant quatre-vingt-dix jours : la règle du retour vaut pour toute la vie. Reprendre après un mois de pause, c'est la même action que reprendre après un jour de pause — plus difficile, mais de même nature.",
 "Enfin, la maintenance pose la question du sens : pourquoi continuer quand plus rien n'est exigé ? La réponse tient en une observation : la qualité de l'attention est la qualité de la vie. Les lectures profondes, les conversations présentes, les décisions claires, les moments habités : tout cela est fait de la même matière — une attention entraînée à rester. La maintenance n'est pas un devoir ; c'est un entretien de la vie. Et cet entretien, une fois intégré, n'est plus un protocole ; c'est une manière d'être. Le programme de quatre-vingt-dix jours finit ; la pratique, elle, ne finit jamais, parce qu'elle n'est pas une étape mais une façon de vivre chaque journée."],
}

LEARNINGS_EXT = {
1: [
 "Il y a un test simple pour vérifier la charge cognitive : si tu dois relire plusieurs fois la même phrase sans la comprendre, si tu oublies ce que tu lisais, ou si tu te sens agité après dix minutes de lecture, la scène est probablement saturée. La première réaction n'est pas de se forcer ; c'est de réduire ce qui occupe la scène : fermer les autres fenêtres, éteindre les notifications, ralentir le rythme. La charge cognitive se gère par l'environnement avant de se gérer par la volonté.",
 "Une application concrète : avant une session, poser la question « qu'est-ce qui va entrer dans la scène pendant que je travaille ? ». La réponse devrait être presque vide : la tâche, et rien d'autre. Les éléments parasites — un onglet ouvert, un téléphone visible, une conversation en cours — sont des charges que l'on ajoute à la tâche. Les retirer n'est pas un confort ; c'est un réglage de la charge. Cette habitude de préparation est aussi importante que la session elle-même, parce qu'elle décide de la qualité de la scène avant que le travail commence."],
2: [
 "Le conditionnement explique aussi pourquoi les environnements fonctionnent mieux que les résolutions : ils agissent sur les déclencheurs, pas sur les intentions. Une résolution dit « je ne vérifierai plus » ; un environnement dit « il n'y a rien à vérifier ». La première dépend de la volonté à chaque instant ; le second agit en continu, sans fatigue. C'est pour cela que les personnes qui réussissent à changer leurs habitudes ne sont pas nécessairement les plus volontaires ; ce sont souvent celles qui ont le mieux aménagé leurs conditions.",
 "Une question pratique : comment reconnaître une pulsion conditionnée avant qu'elle ne devienne un geste ? Les signes sont corporels et rapides : une envie soudaine, une main qui cherche, une pensée du type « et si... ». Ces signes précèdent le geste de moins d'une seconde, mais ils existent. Avec de la pratique, on apprend à les repérer, et le repérage suffit à ralentir le geste. Le ralentissement est la fenêtre dans laquelle la décision peut entrer. Sans repérage, il n'y a pas de fenêtre ; avec repérage, il y a un choix."],
3: [
 "Une méthode pour pratiquer le raisonnement par hypothèses dans la vie ordinaire : la phrase « je crois que X, donc si X est vrai, je devrais observer Y ». Cette phrase force la déduction : une croyance doit produire une conséquence observable. Si la conséquence n'apparaît pas, la croyance doit être révisée. Cette méthode s'applique à l'entraînement lui-même : « je crois que les sessions du matin me conviennent mieux, donc si c'est vrai, mes sessions du matin devraient être plus faciles à tenir ». La trace fournit la donnée, et la donnée révisera la croyance.",
 "Une erreur symétrique à éviter : la sur-correction. Après une seule donnée négative, abandonner l'hypothèse est aussi hâtif que de la confirmer après une seule donnée positive. Une hypothèse sérieuse demande plusieurs tests, dans des conditions variées. L'entraînement à l'attention est un long exercice de ce type : chaque semaine est un petit protocole expérimental, avec des conditions notées et des résultats observés. Le raisonnement par hypothèses n'est pas une abstraction ; c'est la méthode même de la pratique."],
4: [
 "Une précision sur la notion de valeur : le coût d'opportunité ne se mesure pas en quantité de temps, mais en valeur de ce qui est sacrifié. Une heure de flux après une journée de travail a un coût faible : ce que l'on sacrifie, c'est surtout une heure de repos. La même heure de flux le matin sacrifie la meilleure heure de travail de la journée. La valeur n'est pas dans l'activité en soi ; elle est dans l'alternative. Cette relativité explique pourquoi les mêmes comportements peuvent être raisonnables à certains moments et coûteux à d'autres.",
 "Une application pratique : le choix du moment. Le protocole ne dit pas seulement quoi faire ; il dit quand — les sessions sont placées là où la ressource est la plus haute et les sacrifices les plus acceptables. La question du coût d'opportunité devient ainsi un outil de planification : avant d'ouvrir le flux, demander « quelle est la meilleure chose que je pourrais faire avec cette heure ? » et comparer. La réponse n'est pas toujours de travailler ; parfois, c'est de se reposer vraiment. Mais la question, posée honnêtement, transforme les dépenses automatiques en choix."],
5: [
 "Cette vision a une conséquence sur la responsabilité : si le choix dépend des conditions, alors aménager les conditions est une responsabilité. On ne peut pas tout contrôler — il y aura toujours des tentations, des urgences, des imprévus — mais on peut contrôler une partie de l'architecture : ce qui est visible, ce qui est proche, ce qui est proposé. Chaque aménagement est une décision anticipée, prise au moment où l'on est calme, pour le moment où l'on sera tenté. C'est la forme la plus intelligente de la volonté : se préparer à ne pas en avoir besoin.",
 "Une objection à anticiper : ne perd-on pas quelque chose en s'organisant ainsi ? Certains craignent que les cadres rendent la vie rigide. C'est l'inverse : les cadres choisis libèrent l'énergie que la négociation permanente consommait. Une journée avec des moments cadrés est une journée où l'on ne décide pas cent fois la même chose. Les décisions restantes — celles qui comptent — trouvent une attention disponible. La liberté n'est pas dans l'absence de structures ; elle est dans la structure qui protège les choix importants."],
6: [
 "Un point de prudence : la plasticité est parfois présentée comme une promesse de réparation totale — « le cerveau peut tout changer ». Cette présentation est trompeuse. La plasticité a des limites de temps, d'intensité et de direction : elle favorise ce qui est pratiqué, mais elle ne crée pas de capacités nouvelles à partir de rien. Un adulte n'apprendra pas une langue avec la facilité d'un enfant, quelle que soit sa plasticité. La vérité utile est plus modeste et plus solide : la pratique régulière modifie réellement ce qui est pratiqué, dans des proportions observables.",
 "Une application concrète : observer ses propres adaptations sur plusieurs semaines. Les premières sessions sont difficiles ; après quelques semaines, le démarrage devient plus facile, les retours plus rapides, la durée plus tenable. Ces changements sont des adaptations — c'est la plasticité au travail. Les noter, dans la trace ou dans un carnet, transforme un concept scientifique en expérience personnelle. Et cette expérience personnelle est le meilleur antidote aux promesses magiques : elle montre ce que la pratique fait réellement, et ce qu'elle ne fait pas."],
7: [
 "Un exemple de boucle négative utile : la fatigue. Une session difficile produit de la fatigue ; la fatigue non reconnue produit des sessions plus courtes ; les sessions plus courtes produisent moins d'entraînement ; moins d'entraînement produit des sessions encore plus difficiles. Cette boucle peut faire croire que l'on régresse. La sortie n'est pas l'effort supplémentaire ; c'est la pause et la régularité : accepter des sessions modestes, bien dormir, revenir. La boucle négative se casse en changeant une variable, pas en luttant contre le système entier.",
 "Il y a aussi une leçon sur la mesure : une boucle ne se comprend que si l'on voit son circuit. Le protocole rend les boucles visibles : la trace montre les sessions complétées, les retours, les tendances ; le compteur de changements montre la boucle de distraction. Ce qui est visible peut être réaménagé. L'entraînement à l'attention est ainsi un apprentissage de lecture de systèmes : voir ses propres circuits, repérer les points d'interruption, choisir où agir. Cette compétence dépasse le protocole ; elle sert partout où des habitudes se sont formées."],
8: [
 "Un exemple de descente utile dans les couches : la durée de visionnage. L'interface affiche un compteur de temps passé ; c'est une abstraction de niveau un. En dessous, il y a la question de la qualité : ce temps a-t-il produit quelque chose ? En dessous encore, il y a la question du mécanisme : pourquoi ai-je continué ? La réponse — parce que le défilement ne finit pas, parce que chaque contenu propose le suivant — est une couche plus profonde, et c'est elle qui permet d'agir. Descendre d'une couche suffit souvent pour transformer une statistique en décision.",
 "La contre-idée à abandonner n'est pas la technologie ; c'est la passivité de l'utilisateur. On peut utiliser des outils puissants sans en être la matière première, à condition de voir les couches et de faire des choix à partir de cette vision. L'abstraction n'est pas un piège en soi ; c'est un outil qui devient piège quand on confond l'interface avec la réalité. La compétence est de pouvoir monter et descendre : utiliser la simplicité de l'interface quand elle sert, et descendre dans les couches quand une décision importante se joue. C'est cette mobilité qui fait la différence entre subir et maîtriser."],
9: [
 "La saillance a une conséquence sur l'aménagement de l'espace de travail : le champ visuel est plus important que la volonté. Un objet saillant dans le champ périphérique — un téléphone qui s'allume, une notification qui s'affiche — attire l'attention avant que la pensée n'intervienne. L'aménagement consiste à retirer les saillances du champ : appareils hors de vue, notifications désactivées, surfaces épurées. Cette aménagement ne rend pas la concentration automatique, mais il la rend possible : l'attention n'a plus à lutter contre des concurrents visibles.",
 "Il y a aussi une application inverse : utiliser la saillance pour soi. Une tâche rendue visible — une affiche, une liste, un objectif écrit — devient une saillance utile : elle attire le regard vers ce qui compte. Les interfaces du protocole utilisent ce principe : la tâche affichée, la durée visible, le statut clair. La saillance n'est pas mauvaise ; elle est directionnelle. La question n'est pas de supprimer la saillance, c'est de choisir sa direction : vers la tâche, pas vers la distraction. L'entraînement est en partie un aménagement de saillances."],
10: [
 "Il faut examiner le rôle du vocabulaire dans la reformulation. Quand on reformule avec les mots du texte, on ne sait pas toujours si l'on a compris : les mots portent le sens à notre place. Quand on reformule avec ses propres mots, on est obligé de trouver une autre route vers le sens — et la route révèle la compréhension. C'est pour cela que les contraintes de vocabulaire sont utiles en apprentissage : reformuler sans les termes du texte, c'est forcer la reconstruction complète, pas une copie partielle.",
 "Une application pratique : après une lecture, se donner trois contraintes — pas de termes du texte, pas de résumé chronologique, pas de remplissage. La première contrainte force la reformulation ; la seconde force la structure ; la troisième force la sélection. Ces contraintes transforment la restitution en exercice de pensée. Avec la pratique, elles deviennent intérieures : on cesse d'avoir besoin de les énoncer, elles guident la lecture elle-même. La reformulation n'est pas une technique de test ; c'est une technique de lecture — on lit déjà en reconstruisant."],
11: [
 "Le biais de confirmation a une version spécifique à l'entraînement : le biais de la session récente. La dernière session — bonne ou mauvaise — pèse plus que les précédentes dans le jugement. Une mauvaise session hier produit « je régresse » ; une bonne produit « ça y est ». Ce biais est renforcé par l'émotion : la session récente est fraîche, les anciennes sont pâles. La trace corrige ce biais en donnant à toutes les sessions le même poids : la tendance se lit sur la série, pas sur le dernier point.",
 "Une méthode simple pour contrer le biais : la décision différée. Ne pas juger une session le jour même ; attendre trois jours, puis regarder la donnée avec la série. Ce délai permet à l'émotion de retomber et au contexte de se voir : la session difficile avait peut-être des causes identifiables — fatigue, environnement, urgence. Le jugement différé n'est pas une absence de jugement ; c'est un jugement mieux informé. L'entraînement sérieux apprend à se fier à la tendance, pas à l'humeur du moment."],
12: [
 "Il y a une application directe de la rareté à la planification : réserver les moments de haute attention pour les activités qui la méritent. La ressource est la plus haute le matin, après le repos ; c'est le moment des investissements — lecture, apprentissage, décisions importantes. Elle baisse dans la journée ; c'est le moment des activités plus légères et des réparations. Cette répartition n'est pas une contrainte ; c'est une optimisation. Elle reconnaît que l'attention n'est pas uniforme, et que la même activité a une valeur différente selon le moment où elle est placée.",
 "Une nuance importante : la rareté ne doit pas produire une avarice totale. Garder toute son attention pour les « grandes choses » appauvrit les petites, et les petites sont la texture de la vie : une conversation, une promenade, un repas. L'économie de l'attention n'est pas une banque ; c'est une allocation. Le bon usage n'est pas de tout économiser, mais de donner à chaque chose l'attention qu'elle mérite — beaucoup aux choses profondes, un peu aux choses légères, et de ne pas laisser les choses légères voler la part des profondes. C'est la définition d'un budget équilibré."],
13: [
 "Un exercice pour vérifier cette idée : pendant une minute, regarder un objet ordinaire sans rien faire d'autre. La première seconde est facile ; les suivantes deviennent difficiles — l'esprit propose autre chose. Cette difficulté est la preuve que la présence ne va pas de soi : elle doit être soutenue, et elle s'épuise. L'exercice de la minute est une version minuscule de la session : on voit le mécanisme à petite échelle. Ce qui est vrai pour la minute est vrai pour l'heure : la présence est un soutien continu, pas un état acquis.",
 "Il y a une conséquence pratique pour la vie quotidienne : les moments d'attente sont des occasions d'entraînement. Une file, un trajet, une pause : ces moments sont habituellement remplis de flux. Les laisser vides, c'est pratiquer la présence — et c'est aussi récupérer du temps réel : le temps d'attente devient du temps vécu au lieu de temps traversé. L'entraînement à la présence ne demande pas des heures ; il demande de ne pas remplir les interstices. Les interstices, additionnés, sont une part énorme de la journée."],
14: [
 "Une précision sur la durée : la réhabituation prend du temps, et ce temps varie. Certaines personnes retrouvent une tolérance au vide en quelques jours ; d'autres ont besoin de plusieurs semaines. La variation n'est pas un signe d'échec ; elle dépend de l'histoire de l'habituation. Une personne habituée au flux depuis des années a plus de chemin qu'une personne qui a toujours eu des moments calmes. Le protocole tient compte de cette variation en proposant des durées progressives : la tolérance se construit à son propre rythme, sans comparaison.",
 "Il y a un piège à éviter pendant la réhabituation : le remplissage mental. Le vide ne signifie pas « ne penser à rien » ; il signifie « ne pas introduire de stimulus nouveau ». Les pensées qui viennent — souvenirs, projets, inquiétudes — font partie de l'exercice ; les observer est le but. Le piège serait de remplacer le stimulus externe par un stimulus interne : des listes, des plans, des analyses. La session n'est pas un moment de productivité mentale ; c'est un moment d'observation. Cette distinction est subtile, mais elle décide de la nature de l'exercice."],
15: [
 "Il faut aussi parler des boucles qui se croisent : la boucle courte de la distraction et la boucle longue de l'entraînement ne sont pas séparées ; elles se nourrissent. Chaque session complétée affaiblit un peu la boucle courte — le geste de vérifier perd un renforcement — et renforce la boucle longue — la capacité de rester gagne un point. L'inverse est vrai aussi : chaque session manquée renforce la boucle courte. C'est pour cela que la régularité est si importante : elle déplace l'équilibre entre les deux boucles, petit à petit, dans la bonne direction.",
 "Une application de la théorie des boucles à la motivation : les rituels de démarrage. Une boucle longue ne se lance pas toute seule ; elle a besoin d'un déclencheur fiable. Le rituel — même heure, même geste, même préparation — est ce déclencheur. Après quelques semaines, le rituel déclenche la session presque automatiquement : l'énergie de démarrage diminue, la négociation s'efface. Ce n'est pas de la magie ; c'est une boucle bien construite. Ceux qui luttent pour commencer n'ont souvent pas de rituel : ils décident chaque fois, et chaque décision est une bataille. Le rituel est la bataille gagnée d'avance."],
16: [
 "Un exemple concret de conception d'interface : le bouton de fermeture. Une interface de captation rend la fermeture difficile — le bouton est petit, caché, ou absent ; le flux continue. Une interface de protection rend la fermeture facile — un bouton clair, une fin visible, une confirmation. Ce détail technique révèle l'intention : chaque interface choisit ce qu'elle rend facile. Lire les interfaces, c'est d'abord repérer ces choix : qu'est-ce que cette interface rend facile, et qu'est-ce qu'elle rend difficile ? La réponse dit ce qu'elle veut que tu fasses.",
 "La conception des interfaces du protocole suit cette logique inversée : ce qui est rendu facile, c'est la clôture. Le bouton de verrouillage est grand ; la durée est affichée ; la fin est connue. Pendant la session, il n'y a presque aucune interface : un texte, un minuteur, une action. Cette pauvreté est une richesse : l'attention n'est pas sollicitée par des choix. L'utilisateur du protocole apprend, par contraste, à reconnaître la richesse des interfaces de captation — et à la refuser. La connaissance des interfaces est une protection."],
17: [
 "Un exemple concret : la journée de travail. Une journée remplie de réunions, de messages et de changements produit peu de souvenirs cohérents ; une journée avec deux ou trois blocs de travail profond produit des souvenirs organisés. La différence ne vient pas de l'importance des événements ; elle vient du traitement. Les blocs profonds créent des scènes — un début, un milieu, une fin — et les scènes sont la matière des souvenirs. La fragmentation, elle, ne crée pas de scènes ; elle crée des instants sans cadre, que la mémoire ne peut pas ranger.",
 "Il y a une conséquence pratique : la structure de la journée est une structure de mémoire. Prévoir des blocs — même courts — donne à la journée une forme que la mémoire peut retenir. Le soir, la question « qu'ai-je fait aujourd'hui ? » trouve une réponse si la journée a eu des blocs ; elle reste sans réponse si la journée a été un flux. L'entraînement à l'attention n'est donc pas seulement un travail sur la concentration ; c'est un travail sur la mémoire de la vie. Les sessions donnent à la journée sa forme, et la forme donne les souvenirs."],
18: [
 "Une application de la rareté à la lecture : choisir un texte, c'est exclure tous les autres. Ce choix est difficile, parce que l'exclusion est une perte — les autres textes existent, et on ne les lira pas. Mais l'exclusion est aussi la condition de la lecture : un texte ne se lit que si l'on a décidé de ne pas lire les autres pendant ce temps. L'entraînement à choisir est donc un entraînement à accepter la perte : on ne peut pas tout lire, tout regarder, tout faire. Accepter la perte, c'est rendre le choix réel — et le choix réel est ce qui donne de la valeur à ce qui est choisi.",
 "Il y a une nuance psychologique : la peur de choisir vient souvent de la peur de regretter. Si l'on choisit mal, on aura perdu du temps. Cette peur est exagérée par le flux, qui propose toujours une option de plus, comme si la meilleure était juste après. La vérité est plus simple : une option moyenne choisie et exploitée vaut mieux qu'une option parfaite jamais choisie. La rareté enseigne cette vérité : la ressource se dépense en choisissant, pas en attendant le choix parfait. L'entraînement à l'attention est un entraînement à choisir malgré l'incertitude, et à assumer le choix."],
19: [
 "Un exercice pour distinguer intention et automatisme : à la fin de chaque heure, noter une action que l'on a faite avec intention et une action faite par automatisme. Le contraste est instructif : les actions intentionnelles sont rares et souvent liées à un projet ; les actions automatiques sont nombreuses et liées au réflexe. Cet exercice ne demande pas de juger ; il demande de compter. Après quelques jours, le déséquilibre devient visible, et la visibilité ouvre la possibilité de rééquilibrer : introduire plus d'intention dans les moments qui en manquent.",
 "Une nuance sur l'intention : elle ne doit pas être confondue avec le contrôle total. On ne peut pas tout décider, ni tout prévoir ; l'intention n'est pas un plan rigide. Elle est une direction qui tolère les imprévus. Une session commencée avec intention peut être interrompue par un événement réel ; l'intention permet de revenir, pas de refuser la réalité. Cette souplesse distingue l'intention de l'obsession : l'une oriente, l'autre enferme. L'entraînement vise la première, et la première seule."],
20: [
 "Une précision sur les tâches automatiques : elles ne sont pas toutes équivalentes. Certaines libèrent l'esprit — marcher, plier, conduire sur un trajet connu ; d'autres le capturent — vérifier, trier, répondre. La distinction est importante : les premières peuvent s'associer à une pensée utile ; les secondes remplacent la pensée. Le problème n'est pas de faire deux choses ; c'est que l'une des deux soit une capture. L'entraînement à l'attention apprend à reconnaître cette différence et à ne pas habiller les captures du costume des tâches automatiques.",
 "Il y a une application quotidienne : choisir consciemment les combinaisons. Marcher en écoutant un texte, plier en réfléchissant à un problème : ces combinaisons sont des gains. Regarder un écran en écoutant quelqu'un, travailler en vérifiant ses messages : ces combinaisons sont des pertes, même si elles semblent productives. La règle n'est pas l'interdiction ; c'est le tri. Chaque combinaison mérite la question : qu'est-ce que cette simultanéité me coûte, et qu'est-ce qu'elle me rapporte ? La réponse, posée régulièrement, transforme des automatismes en choix."],
21: [
 "Une conséquence pratique de l'échantillon : la règle des trois. Trois sessions ne prouvent rien ; trois semaines commencent à dessiner une tendance ; trois mois permettent de parler d'un changement. Cette règle n'est pas une science exacte, mais elle protège des verdicts prématurés. Quand une impression forte apparaît — « je régresse », « ça ne marche pas » — la réponse n'est pas de la croire ou de la nier ; c'est de regarder l'échantillon : combien de données ai-je réellement ? Si la réponse est petite, l'impression est un signal, pas une conclusion.",
 "Il y a aussi une application dans le sens inverse : les généralisations positives. Une bonne semaine ne prouve pas que tout est résolu ; elle est une donnée encourageante dans une série plus longue. Le protocole traite les succès et les échecs de la même façon — comme des données — et c'est cette symétrie qui protège la pratique. Celui qui croit trop vite à ses succès relâche ; celui qui croit trop vite à ses échecs abandonne. La trace, elle, ne croit ni à l'un ni à l'autre : elle accumule, et c'est l'accumulation qui parle."],
22: [
 "Il y a une objection à la logique du coût marginal : elle semble exiger de tout interrompre dès que la valeur baisse, ce qui est impossible et épuisant. La réponse est dans le mot « décision » : le coût marginal n'oblige pas à tout arrêter ; il oblige à remarquer. Remarquer que la valeur baisse n'est pas une obligation d'agir immédiatement ; c'est une invitation à choisir en connaissance de cause. On peut décider de rester — pour finir, pour une raison, par plaisir — mais alors on reste parce qu'on a choisi, pas parce qu'on n'a pas vu.",
 "Une application concrète : les fins de session. Les dix dernières minutes d'une session ont un coût marginal différent des premières : la fatigue monte, l'attention vacille, et pourtant c'est là que la discipline se construit. Le coût marginal ne dit pas de s'arrêter avant la fin ; il dit de savoir pourquoi on continue. Continuer pour finir ce que l'on a commencé, continuer pour s'entraîner à la fin difficile, continuer par plaisir : ce sont des raisons réelles. La seule raison pauvre est « je n'ai pas remarqué que ça ne valait plus »."],
23: [
 "La phénoménologie a une application dans le choix des exercices : si une pratique ne produit aucune sensation — ni effort, ni fluidité, ni satisfaction — elle risque de devenir vide. La sensation n'est pas la preuve du travail, mais son absence est un signal. Un bon entraînement alterne les textures : des sessions où l'on sent l'effort, des sessions où l'on sent la fluidité, des sessions où l'on sent simplement la durée passer. Cette variété phénoménologique est un signe de vie ; une pratique qui ne produit qu'une seule sensation s'est probablement figée.",
 "Il y a une question à se poser régulièrement : « qu'est-ce que je ressens pendant mes sessions ? ». La réponse change avec le temps : au début, de l'effort et de la tension ; plus tard, une stabilité et parfois de la légèreté. Cette évolution est la récompense réelle de l'entraînement, et elle ne se voit pas dans les chiffres. Le protocole lui donne une place à travers les questions subjectives — calme, énergie, ce qui a changé. Ces questions ne sont pas un supplément sentimental ; elles sont une mesure de la dimension vécue, sans laquelle l'entraînement n'est qu'une mécanique."],
24: [
 "Un exemple de conditions favorables : la lecture d'un texte légèrement difficile, avec une marge de progression. Trop facile, la lecture s'ennuie ; trop difficile, elle décourage ; juste au-dessus du niveau actuel, elle engage. Cette zone est celle de l'absorption : l'attention y trouve une difficulté qui la remplit sans la dépasser. Le protocole organise cette zone en faisant progresser les durées et les contenus par paliers : chaque palier est un défi légèrement supérieur, calculé pour rester dans la zone.",
 "Il faut aussi reconnaître que l'absorption n'est pas l'objectif de chaque session. Certaines sessions seront laborieuses du début à la fin ; elles comptent quand même, parce qu'elles construisent la capacité de rester dans le laborieux. L'absorption est un état possible, pas une exigence. La différence entre un pratiquant et un amateur est peut-être là : l'amateur ne s'entraîne que quand l'état vient ; le pratiquant s'entraîne aussi quand il ne vient pas. Et c'est précisément cette constance qui rend l'état plus fréquent."],
25: [
 "Un exemple d'incitation réelle : la session elle-même. Une session de concentration a des récompenses réelles — la sensation d'avoir tenu, la trace qui s'accumule, la capacité qui grandit — mais ces récompenses sont lointaines et diffuses. Pour qu'elles agissent comme incitations, il faut les rapprocher : rendre la complétion visible, noter la tendance, célébrer sobrement les étapes. Le protocole le fait avec la trace et la progression du jour. L'incitation n'est pas factice ; elle est la visibilité d'une récompense réelle.",
 "La contre-idée à abandonner est la croyance que les récompenses factices — points, badges, séries — peuvent remplacer les récompenses réelles. Elles peuvent les imiter un temps, mais elles s'épuisent, parce qu'elles ne produisent rien de réel. Une série de jours parfaits ne construit pas une capacité ; elle construit une peur de la rupture. Une session tenue construit une capacité, et la trace le montre. Le protocole choisit délibérément les incitations réelles : pas de points, pas de badges, pas de séries — seulement des sessions, des données et une tendance. C'est moins brillant, et cela dure."],
26: [
 "Un exemple de patience épistémique : l'apprentissage d'un concept difficile. La première lecture produit une impression de compréhension ; la première reformulation révèle des trous ; la deuxième lecture comble certains trous ; la deuxième reformulation en révèle d'autres. Ce processus n'est pas un défaut ; c'est la mécanique même de la compréhension. Celui qui s'arrête à la première impression reste avec une compréhension fragile ; celui qui accepte les trous et revient construit une compréhension solide. La différence n'est pas l'intelligence ; c'est la patience.",
 "Il y a une émotion à apprivoiser dans ce processus : l'humiliation de ne pas comprendre. Elle est presque toujours exagérée — on croit être le seul, on croit que c'est une preuve d'incapacité. La vérité est plus banale : ne pas comprendre est l'état normal de l'apprentissage, et tout le monde le traverse, à des vitesses différentes. La patience épistémique consiste à laisser l'humiliation passer, comme on laisse la confusion passer, et à revenir au travail. L'entraînement à la reconstruction est un entraînement à cette traversée : les trous sont montrés, acceptés, et repris."],
27: [
 "Une application de la théorie des systèmes adaptatifs à soi-même : observer ses propres règles locales. Le geste de vérifier au réveil, l'ouverture du flux pendant les repas, le changement de tâche au premier ennui : chacune de ces règles est une ligne de code personnelle, invisible, exécutée automatiquement. L'entraînement à l'attention est une révision de ces règles : en examiner une, décider si elle sert, la remplacer par une autre. Cette révision n'est pas une décision ponctuelle ; c'est un processus continu, comme la mise à jour d'un système.",
 "Il y a une leçon sur les objectifs des systèmes : un système adaptatif n'a pas de morale, il a une direction. L'algorithme qui optimise la durée de présence n'est ni bon ni mauvais ; il est directionnel. Le protocole, lui, optimise autre chose — la capacité de maintien, la profondeur, la régularité. Deux systèmes optimisent en parallèle, et le résultat dépend de celui que l'on nourrit. Nourrir un système, c'est lui donner du comportement : du temps, des clics, des réponses. La question quotidienne est donc : quel système ai-je nourri aujourd'hui ?"],
28: [
 "Un exemple concret d'information réelle : une décision à prendre. Une information est réelle si elle change la décision — le prix d'un billet, la date d'un rendez-vous, le résultat d'une analyse. Tout le reste — les actualités sans conséquence, les contenus sans lien avec nos choix — est de la stimulation. Cette définition n'est pas une injonction à l'austérité ; elle est un instrument de tri. Avant de consommer un contenu, demander : qu'est-ce que cela pourrait changer dans mes décisions ? Si la réponse est « rien », c'est de la stimulation, et la stimulation a sa place — mais une place choisie, pas une place dominante.",
 "Il y a une conséquence sur la lecture : un texte long a plus de chances de contenir de l'information réelle, parce qu'il développe des arguments que le format court ne peut pas porter. La lecture profonde n'est pas un luxe ; c'est le format le plus dense en information réelle. Le protocole organise cette lecture et la reconstruction qui la vérifie. La reconstruction est le test d'information : ce qui reste après la fermeture est ce qui a réellement changé quelque chose. Le reste était du bruit, même s'il était agréable."],
29: [
 "Un exemple de dosage dans l'entraînement : les premières semaines. Elles sont exploratoires : essayer les modes, découvrir les durées, comprendre ses réactions. C'est de l'exploration nécessaire, mais elle doit être bornée : après quelques semaines, la phase d'exploitation commence — choisir un rythme, tenir, approfondir. Le protocole organise cette transition naturellement : les phases ajoutent de la durée et de la profondeur au fur et à mesure. L'exploration reste disponible — le choix des disciplines — mais elle ne domine plus la pratique.",
 "Il y a une erreur symétrique à éviter : l'exploitation sans exploration, qui mène à la routine. Une pratique qui répète les mêmes modes, les mêmes contenus, les mêmes conditions finit par s'engourdir. La solution est une exploration bornée et régulière : changer un paramètre de temps en temps — un nouveau texte, une nouvelle durée, une nouvelle heure — sans changer le cadre. Cette exploration légère renouvelle la pratique sans la fragiliser. L'équilibre entre explorer et exploiter se règle ainsi : une base stable, et des variations choisies."],
30: [
 "Un exemple de désirabilité : le choix de la tâche. Une session de concentration est plus désirable quand la tâche est choisie pour elle-même — un sujet qui intéresse, un travail qui compte — que quand elle est imposée. Cette différence ne rend pas la session plus facile, mais elle la rend plus attirante : on va vers elle au lieu de s'y traîner. Le protocole laisse le choix de la tâche, dans les limites du mode du jour. Cette liberté n'est pas un luxe ; c'est un réglage de motivation.",
 "Il y a une nuance : la désirabilité ne doit pas devenir une exigence. Attendre d'avoir envie de chaque session, c'est s'exposer aux jours sans envie — et ces jours existent. La pratique sérieuse distingue l'envie de démarrer et la décision de commencer : on peut commencer sans envie, et l'envie vient parfois pendant. La désirabilité est un levier, pas une condition. Le protocole combine les deux : il rend les sessions aussi désirables que possible, et il organise la régularité pour les jours où l'envie manque. C'est ainsi qu'une pratique reste vivante sans dépendre de l'humeur."],
31: [
 "Une application de l'émergence à l'attention individuelle : les règles locales créent des états globaux. La règle « vérifier quand le téléphone s'allume » crée l'état global de la vérification permanente ; la règle « fermer l'onglet avant d'en ouvrir un autre » crée l'état global de l'environnement allégé. On ne se donne pas d'ordre global — « sois concentré » — ; on installe des règles locales, et l'état global émerge. Cette méthode est plus efficace, parce qu'elle agit là où le comportement se produit : au niveau de la règle, pas au niveau du résultat.",
 "Il y a une leçon sur la contagion : les règles locales sont contagieuses. Un environnement où l'on ferme les onglets, où l'on pose les téléphones, où l'on laisse les phrases finir, influence ceux qui le partagent. L'attention n'est pas seulement individuelle ; elle est collective, et elle émerge des règles partagées. Chaque personne qui installe une règle d'attention contribue à un état collectif. Cette perspective change la portée de la pratique : elle n'est pas seulement personnelle, elle est aussi un cadeau à l'environnement. Les règles simples, répétées, finissent par créer des mondes."],
32: [
 "Une application de la théorie des affordances au design des sessions : rendre la clôture visible. Une session bien conçue a des affordances de fin : une durée affichée, un signal de complétion, un bouton de clôture. Ces éléments ne sont pas décoratifs ; ils invitent le geste de fermer, et le geste de fermer est la compétence que l'on entraîne. L'entraînement à l'attention est aussi un entraînement à fermer : fermer la session, fermer l'application, fermer la journée. Chaque clôture est une répétition de la décision de s'arrêter.",
 "Il y a une leçon inverse : les affordances de captation sont partout, et les reconnaître est un réflexe à développer. Un point rouge, un badge, un compteur, une suggestion : chacune de ces formes est une invitation dessinée. Le réflexe de lecture consiste à se demander, devant chaque invitation : qu'est-ce que cette forme veut que je fasse ? La réponse est presque toujours la même — rester, ouvrir, vérifier. La reconnaissance ne supprime pas l'invitation, mais elle la transforme : on ne la suit plus aveuglément, on la voit. Et voir une invitation, c'est déjà choisir de la refuser."],
33: [
 "Une application de la variance à la planification : les jours difficiles sont des points de variance, et leur gestion décide de la qualité de la série. Un jour difficile peut être traité de deux façons : comme une rupture (on abandonne, on attend le lendemain) ou comme une donnée (on fait une session courte, on note les conditions, on continue). La première augmente la variance ; la seconde la limite. Le protocole prévoit cette gestion par la règle du retour : la session peut être plus courte, mais elle compte. La variance se réduit par la régularité des petites complétions.",
 "Il y a une nuance : la variance n'est pas toujours l'ennemie. Une pratique qui varie ses conditions — heures, lieux, modes — développe une robustesse que la pratique monochrome n'a pas. La variance choisie est un entraînement ; la variance subie est une fragmentation. La différence est dans le contrôle : varie ce que tu choisis de varier, et stabilise ce que tu choisis de stabiliser. L'entraînement à l'attention est un réglage de cette balance : une base stable pour la régularité, des variations choisies pour la robustesse, et une trace pour lire la tendance réelle."],
34: [
 "Une application du temps vécu : la perception des sessions change avec l'entraînement. Au début, dix minutes semblent longues : chaque minute pèse, l'attention lutte. Après des semaines, les mêmes dix minutes semblent courtes : l'esprit entre plus vite dans la tâche, la durée passe presque sans friction. Cette évolution n'est pas seulement subjective ; elle est un indicateur réel du changement. Le temps vécu est un instrument de mesure : quand la durée cesse de peser, quelque chose s'est transformé.",
 "Il y a une conséquence sur les statistiques : les compteurs d'usage mesurent le temps horloge, pas le temps vécu. Deux heures de flux et deux heures de présence ont la même durée horloge et des vécus opposés. Le protocole ne mesure pas le temps horloge pour juger ; il mesure les complétions, les retours, les tendances — des données qui approchent le vécu. Et les questions subjectives — calme, énergie, ce qui a changé — mesurent directement la texture. Cette double mesure, objective et vécue, est la seule qui rende justice à l'entraînement."],
35: [
 "Un exemple de maintenance concrète : le calendrier hebdomadaire. Trois sessions par semaine, à des moments fixes, avec des modes en rotation : ce petit cadre suffit à entretenir la capacité. Il ne demande pas de décision à chaque session — la décision a été prise une fois, pour la semaine. Il laisse de la place à la vie — les imprévus, les voyages, les semaines chargées — parce qu'il n'exige pas la perfection. La maintenance n'est pas un second protocole ; c'est un cadre minimal, et sa légèreté est sa force.",
 "Il y a une dernière considération : le sens de la maintenance change avec le temps. Au début, on s'entraîne pour construire ; ensuite, on s'entraîne pour maintenir ; enfin, on s'entraîne parce que la pratique est devenue une partie de soi. Cette évolution n'est pas une perte d'intensité ; c'est une intégration. La pratique n'est plus un projet ; c'est une habitude de vie, comme dormir et manger. Le mode CORE formalise cette étape, mais il ne la crée pas ; il la reconnaît. La fin du protocole n'est pas une fin ; c'est le début de la pratique comme vie."],
}

def load(name):
    with open(os.path.join(CONTENT, f"{name}.json")) as f:
        return json.load(f)

def save(name, data):
    with open(os.path.join(CONTENT, f"{name}.json"), "w") as f:
        f.write("[\n")
        f.write(",\n".join(json.dumps(entry, ensure_ascii=False) for entry in data))
        f.write("\n]\n")

def main():
    readings = load("readings")
    for entry in readings:
        extra = READINGS_EXT.get(entry["id"])
        if extra:
            entry["text"] = entry["text"] + "\n\n" + "\n\n".join(extra)
    save("readings", readings)
    print(f"readings extended: {sum(1 for e in readings if e['id'] in READINGS_EXT)}")

    learnings = load("learnings")
    for entry in learnings:
        extra = LEARNINGS_EXT.get(entry["id"])
        if extra:
            entry["text"] = entry["text"] + "\n\n" + "\n\n".join(extra)
    save("learnings", learnings)
    print(f"learnings extended: {sum(1 for e in learnings if e['id'] in LEARNINGS_EXT)}")

if __name__ == "__main__":
    main()
